using System.Numerics;
using Content.Client.Computer;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Gateway;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Gateway.UI;

[GenerateTypedNameReferences]
public sealed partial class GatewayWindow : FancyWindow,
    IComputerWindow<EmergencyConsoleBoundUserInterfaceState>
{
    private readonly IGameTiming _timing;

    public event Action<NetEntity>? OpenPortal;
    private List<GatewayDestinationData> _destinations = new();
    private readonly List<(Label Label, GatewayDestinationData Destination)> _rotationLabels = new();

    public NetEntity Owner;

    private NetEntity? _current;
    private TimeSpan _nextReady;
    private TimeSpan _cooldown;

    private TimeSpan _unlockTime;
    private TimeSpan _nextUnlock;

    /// <summary>
    /// Re-apply the state if the timer has elapsed.
    /// </summary>
    private GatewayBoundUserInterfaceState? _lastState;

    /// <summary>
    /// Are we currently waiting on an unlock timer.
    /// </summary>
    private bool _isUnlockPending = true;

    /// <summary>
    /// Are we currently waiting on a cooldown timer.
    /// </summary>
    private bool _isCooldownPending = true;

    public GatewayWindow()
    {
        RobustXamlLoader.Load(this);
        var dependencies = IoCManager.Instance!;
        _timing = dependencies.Resolve<IGameTiming>();

        NextUnlockBar.ForegroundStyleBoxOverride = new StyleBoxFlat(Color.FromHex("#C74EBD"));
    }

    public void SetEntity(NetEntity entity)
    {
        Owner = entity;
    }

    public void UpdateState(GatewayBoundUserInterfaceState state)
    {
        _destinations = state.Destinations;
        _current = state.Current;
        _nextReady = state.NextReady;
        _cooldown = state.Cooldown;
        _unlockTime = state.UnlockTime;
        _nextUnlock = state.NextUnlock;

        _isUnlockPending = _nextUnlock >= _timing.CurTime;
        _isCooldownPending = _nextReady >= _timing.CurTime;

        Container.DisposeAllChildren();
        _rotationLabels.Clear();
        _lastState = state;

        if (_destinations.Count == 0)
        {
            Container.AddChild(new BoxContainer()
            {
                HorizontalExpand = true,
                VerticalExpand = true,
                Children =
                {
                    new Label()
                    {
                        Text = Loc.GetString("gateway-window-no-destinations"),
                        HorizontalAlignment = HAlignment.Center
                    }
                }
            });
            return;
        }

        var now = _timing.CurTime;

        foreach (var dest in _destinations)
        {
            var ent = dest.Entity;
            var name = dest.Name;
            var locked = dest.Locked && _nextUnlock > _timing.CurTime;

            var card = new BoxContainer()
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(8f, 7f),
            };

            var header = new BoxContainer()
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
            };

            var nameLabel = new RichTextLabel()
            {
                VerticalAlignment = VAlignment.Center,
                SetWidth = 220f,
            };

            nameLabel.SetMessage(name);
            header.AddChild(nameLabel);
            header.AddChild(new Control()
            {
                HorizontalExpand = true,
            });

            bool Pressable() => ent == _current || ent == Owner;

            var buttonStripe = new StripeBack()
            {
                Visible = locked,
                HorizontalExpand = true,
                VerticalExpand = true,
                Margin = new Thickness(10f, 0f, 0f, 0f),
                Children =
                {
                    new Label()
                    {
                        Text = Loc.GetString("gateway-window-locked"),
                        HorizontalAlignment = HAlignment.Center,
                        VerticalAlignment = VAlignment.Center,
                    }
                }
            };

            var openButton = new Button()
            {
                Text = Loc.GetString("gateway-window-open-portal"),
                Pressed = Pressable(),
                ToggleMode = true,
                Disabled = now < _nextReady || Pressable(),
                HorizontalAlignment = HAlignment.Right,
                Margin = new Thickness(10f, 0f, 0f, 0f),
                Visible = !locked,
                SetHeight = 32f,
            };

            openButton.OnPressed += args =>
            {
                OpenPortal?.Invoke(ent);
            };

            if (Pressable())
            {
                openButton.AddStyleClass(StyleBase.ButtonCaution);
            }

            var buttonContainer = new BoxContainer()
            {
                Children =
                {
                    buttonStripe,
                    openButton,
                },
                SetSize = new Vector2(128f, 40f),
            };

            header.AddChild(buttonContainer);
            card.AddChild(header);

            if (dest.HasIntel)
            {
                var profileLabel = new Label
                {
                    Text = Loc.GetString(dest.ProfileName),
                    ModulateSelfOverride = dest.AccentColor,
                    Margin = new Thickness(0f, 4f, 0f, 1f),
                };
                profileLabel.AddStyleClass(StyleBase.StyleClassLabelHeading);
                card.AddChild(profileLabel);

                var description = new RichTextLabel
                {
                    HorizontalExpand = true,
                    Margin = new Thickness(0f, 0f, 0f, 5f),
                };
                description.SetMessage(FormattedMessage.FromUnformatted(Loc.GetString(dest.ProfileDescription)));
                card.AddChild(description);

                var intel = new GridContainer
                {
                    Columns = 2,
                    HorizontalExpand = true,
                };
                AddIntelRow(intel, "gateway-window-address", dest.Address);
                AddIntelRow(intel, "gateway-window-biome", Loc.GetString(dest.BiomeName));
                AddIntelRow(intel, "gateway-window-weather", Loc.GetString(dest.WeatherName));
                AddIntelRow(intel, "gateway-window-atmosphere", Loc.GetString(dest.AtmosphereName));
                AddIntelRow(intel, "gateway-window-resources", Loc.GetString(dest.Resources));
                AddIntelRow(intel, "gateway-window-hostiles", Loc.GetString(dest.Hostiles));
                AddIntelRow(intel, "gateway-window-threat", GetThreatText(dest.Threat), dest.AccentColor);
                card.AddChild(intel);

                var rotationLabel = new Label
                {
                    Text = GetRotationText(dest, now),
                    Margin = new Thickness(0f, 7f, 0f, 0f),
                    ModulateSelfOverride = Color.LightGray,
                };
                card.AddChild(rotationLabel);
                _rotationLabels.Add((rotationLabel, dest));
            }

            Container.AddChild(new PanelContainer()
            {
                PanelOverride = new StyleBoxFlat(new Color(30, 30, 34)),
                Margin = new Thickness(10f, 5f),
                Children =
                {
                    card
                }
            });
        }
    }

    private static void AddIntelRow(
        GridContainer grid,
        string labelLoc,
        string value,
        Color? valueColor = null)
    {
        grid.AddChild(new Label
        {
            Text = Loc.GetString(labelLoc),
            Margin = new Thickness(0f, 1f, 12f, 1f),
            ModulateSelfOverride = Color.Gray,
        });
        grid.AddChild(new Label
        {
            Text = value,
            HorizontalExpand = true,
            Margin = new Thickness(0f, 1f),
            ModulateSelfOverride = valueColor ?? Color.White,
        });
    }

    private static string GetThreatText(GatewayThreatLevel threat)
    {
        var level = threat switch
        {
            GatewayThreatLevel.Minimal => "gateway-window-threat-minimal",
            GatewayThreatLevel.Low => "gateway-window-threat-low",
            GatewayThreatLevel.Moderate => "gateway-window-threat-moderate",
            GatewayThreatLevel.High => "gateway-window-threat-high",
            GatewayThreatLevel.Extreme => "gateway-window-threat-extreme",
            _ => "gateway-window-threat-unknown",
        };

        return Loc.GetString(
            "gateway-window-threat-value",
            ("rating", new string('◆', Math.Clamp((int)threat, 1, 5))),
            ("level", Loc.GetString(level)));
    }

    private static string GetRotationText(GatewayDestinationData destination, TimeSpan now)
    {
        if (!destination.Loaded)
            return Loc.GetString("gateway-window-rotation-unopened");

        return destination.RotationState switch
        {
            GatewayDestinationRotationState.Scheduled => Loc.GetString(
                "gateway-window-rotation-scheduled",
                ("time", FormatRemaining(destination.RotationAt - now))),
            GatewayDestinationRotationState.EmptyGracePeriod => Loc.GetString(
                "gateway-window-rotation-empty",
                ("time", FormatRemaining(destination.RotationAt - now))),
            GatewayDestinationRotationState.WaitingForClearance =>
                Loc.GetString("gateway-window-rotation-waiting"),
            _ => Loc.GetString("gateway-window-rotation-disabled"),
        };
    }

    private static string FormatRemaining(TimeSpan remaining)
    {
        if (remaining < TimeSpan.Zero)
            remaining = TimeSpan.Zero;

        return remaining.TotalHours >= 1d
            ? $"{(int)remaining.TotalHours:00}:{remaining.Minutes:00}:{remaining.Seconds:00}"
            : $"{remaining.Minutes:00}:{remaining.Seconds:00}";
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var now = _timing.CurTime;
        var dirtyState = false;

        foreach (var (label, destination) in _rotationLabels)
        {
            label.Text = GetRotationText(destination, now);
        }

        // if its not going to close then show it as empty
        if (_nextUnlock == TimeSpan.Zero)
        {
            NextUnlockBar.Value = 1f;
            NextUnlockText.Text = "00:00";
        }
        else
        {
            var remaining = _nextUnlock - now;
            if (remaining < TimeSpan.Zero)
            {
                if (_isUnlockPending)
                {
                    dirtyState = true;
                    _isUnlockPending = false;
                }

                NextUnlockBar.Value = 1f;
                NextUnlockText.Text = "00:00";
            }
            else
            {
                NextUnlockBar.Value = 1f - (float)(remaining.TotalSeconds / _unlockTime.TotalSeconds);
                NextUnlockText.Text = $"{remaining.Minutes:00}:{remaining.Seconds:00}";
            }
        }

        // if its not going to close then show it as empty
        if (_current == null || _cooldown == TimeSpan.Zero)
        {
            NextReadyBar.Value = 1f;
            NextCloseText.Text = "00:00";
        }
        else
        {
            var remaining = _nextReady - now;
            if (remaining < TimeSpan.Zero)
            {
                if (_isCooldownPending)
                {
                    dirtyState = true;
                    _isCooldownPending = false;
                }

                NextReadyBar.Value = 1f;
                NextCloseText.Text = "00:00";
            }
            else
            {
                NextReadyBar.Value = 1f - (float)(remaining.TotalSeconds / _cooldown.TotalSeconds);
                NextCloseText.Text = $"{remaining.Minutes:00}:{remaining.Seconds:00}";
            }
        }

        if (dirtyState && _lastState != null)
        {
            // Refresh UI buttons.
            UpdateState(_lastState);
        }
    }
}
