using System.Linq;
using System.Numerics;
using Content.Client.Shuttles.Components;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class DockingScreen : BoxContainer
{
    [Dependency] private IEntityManager _entManager = default!;

    /// <summary>
    /// Stored by GridID then by docks
    /// </summary>
    public Dictionary<NetEntity, List<DockingPortState>> Docks = new();

    /// <summary>
    /// Store the dock buttons for the side buttons.
    /// </summary>
    private readonly Dictionary<NetEntity, Button> _ourDockButtons = new();

    private readonly ButtonGroup _ftlLockButtonGroup = new();

    public event Action<NetEntity, NetEntity>? DockRequest;
    public event Action<NetEntity, NetEntity>? UndockRequest;
    public event Action? UndockAllRequest;
    public event Action<bool>? ToggleFTLLockRequest;

    public DockingScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        DockingControl.OnViewDock += OnView;
        DockingControl.DockRequest += (entity, netEntity) =>
        {
            DockRequest?.Invoke(entity, netEntity);
        };
        DockingControl.UndockRequest += (entity, target) =>
        {
            UndockRequest?.Invoke(entity, target);
        };

        // Set up FTL Lock buttons
        FTLLockEnabledButton.Group = _ftlLockButtonGroup;
        FTLLockDisabledButton.Group = _ftlLockButtonGroup;

        FTLLockEnabledButton.OnPressed += _ => OnFTLLockPressed(true);
        FTLLockDisabledButton.OnPressed += _ => OnFTLLockPressed(false);

        UndockAllButton.OnPressed += _ => ShowUndockAllConfirmation();
        UndockAllCancelButton.OnPressed += _ => SetUndockAllConfirmation(false);
        UndockAllConfirmButton.OnPressed += _ => OnUndockAllConfirmed();
    }

    private void ShowUndockAllConfirmation()
    {
        if (!HasDockedPorts())
            return;

        SetUndockAllConfirmation(true);
    }

    private void OnUndockAllConfirmed()
    {
        SetUndockAllConfirmation(false);

        if (UndockAllRequest == null || !HasDockedPorts())
            return;

        UndockAllRequest.Invoke();
    }

    private bool HasDockedPorts()
    {
        if (DockingControl.GridEntity == null)
            return false;

        var netEntity = _entManager.GetNetEntity(DockingControl.GridEntity.Value);
        if (!Docks.TryGetValue(netEntity, out var shuttleDocks))
            return false;

        return shuttleDocks.Any(dock => dock.Connected);
    }

    private void SetUndockAllConfirmation(bool visible)
    {
        UndockAllConfirmation.Visible = visible;
        UndockAllButton.Visible = !visible;
    }

    private void OnFTLLockPressed(bool enabled)
    {
        if (ToggleFTLLockRequest == null || DockingControl.GridEntity == null)
            return;

        ToggleFTLLockRequest.Invoke(enabled);
    }

    private void OnView(NetEntity obj)
    {
        if (_ourDockButtons.TryGetValue(obj, out var viewed))
        {
            viewed.Pressed = true;
        }
    }

    public void UpdateState(EntityUid? shuttle, DockingInterfaceState state)
    {
        Docks = state.Docks;
        DockingControl.DockState = state;
        DockingControl.GridEntity = shuttle;
        BuildDocks(shuttle);

        // Enable the destructive action only while it can do useful work.
        var hasDockedPorts = HasDockedPorts();

        UndockAllButton.Disabled = !hasDockedPorts;
        if (!hasDockedPorts)
            SetUndockAllConfirmation(false);

        // Update FTL Lock button appearance based on the lock status of docked shuttles
        UpdateFTLLockButton(shuttle);

    }

    private void UpdateFTLLockButton(EntityUid? shuttle)
    {
        if (shuttle == null)
        {
            FTLLockStatus.Text = Loc.GetString("shuttle-console-ftl-lock-status-unknown");
            return;
        }

        var states = new List<bool> { IsFTLLockEnabled(shuttle.Value) };
        var netEntity = _entManager.GetNetEntity(shuttle.Value);
        if (Docks.TryGetValue(netEntity, out var shuttleDocks))
        {
            states.AddRange(shuttleDocks
                .Where(d => d.Connected && d.GridDockedWith != null)
                .Select(d => IsFTLLockEnabled(_entManager.GetEntity(d.GridDockedWith!.Value))));
        }

        var anyDisabled = states.Any(enabled => !enabled);
        var anyEnabled = states.Any(enabled => enabled);

        if (anyDisabled && !anyEnabled)
        {
            FTLLockDisabledButton.Pressed = true;
            FTLLockEnabledButton.Pressed = false;
            FTLLockStatus.Text = Loc.GetString("shuttle-console-ftl-lock-status-disabled");
            return;
        }

        FTLLockEnabledButton.Pressed = true;
        FTLLockDisabledButton.Pressed = false;
        FTLLockStatus.Text = Loc.GetString(anyDisabled && anyEnabled
            ? "shuttle-console-ftl-lock-status-mixed"
            : "shuttle-console-ftl-lock-status-enabled");
    }

    private bool IsFTLLockEnabled(EntityUid grid)
    {
        return !_entManager.TryGetComponent<FTLLockComponent>(grid, out var lockComp) || lockComp.Enabled;
    }

    private void BuildDocks(EntityUid? shuttle)
    {
        DockingControl.BuildDocks(shuttle);
        var currentDock = DockingControl.ViewedDock;
        // DockedWith.DisposeAllChildren();
        DockPorts.DisposeAllChildren();
        _ourDockButtons.Clear();
        DockPortsEmpty.Visible = true;
        DockPortsStatus.Text = Loc.GetString("shuttle-console-dock-ports-status-empty");

        if (shuttle == null)
        {
            DockingControl.SetViewedDock(null);
            DockPortsStatus.Text = Loc.GetString("shuttle-console-dock-ports-status-unavailable");
            return;
        }

        var shuttleNent = _entManager.GetNetEntity(shuttle.Value);

        if (!Docks.TryGetValue(shuttleNent, out var shuttleDocks) || shuttleDocks.Count <= 0)
            return;

        var connectedCount = shuttleDocks.Count(dock => dock.Connected);
        DockPortsEmpty.Visible = false;
        DockPortsStatus.Text = Loc.GetString("shuttle-console-dock-ports-status",
            ("total", shuttleDocks.Count),
            ("connected", connectedCount));

        var buttonGroup = new ButtonGroup();
        var selected = false;
        DockingPortState? firstState = null; // Frontier

        // Build the dock buttons for our docks.
        foreach (var dock in shuttleDocks.OrderBy(x => x.LabelName ?? x.Name)) // Frontier: order by name
        {
            firstState ??= dock;

            var button = new ShuttleConsoleButton()
            {
                ToggleMode = true,
                Group = buttonGroup,
                Margin = new Thickness(0f, 3f),
                HorizontalExpand = true,
                ToolTip = dock.LabelName ?? dock.Name,
            };

            var buttonContents = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                SeparationOverride = 7,
            };
            buttonContents.AddChild(new ShuttleConsoleIcon
            {
                Kind = ShuttleConsoleIconKind.Docking,
                MinSize = new Vector2(18f, 18f),
            });
            buttonContents.AddChild(new Label
            {
                Text = dock.LabelName ?? dock.Name,
                HorizontalExpand = true,
                ClipText = true,
                FontColorOverride = Color.FromHex("#D7E5E3"),
            });
            buttonContents.AddChild(new Label
            {
                Text = Loc.GetString(dock.Connected
                    ? "shuttle-console-dock-port-state-connected"
                    : "shuttle-console-dock-port-state-free"),
                HorizontalAlignment = HAlignment.Right,
                FontColorOverride = dock.Connected
                    ? Color.FromHex("#A9E3C7")
                    : Color.FromHex("#829597"),
            });
            button.AddChild(buttonContents);

            button.OnMouseEntered += args =>
            {
                DockingControl.HighlightedDock = dock.Entity;
            };

            button.OnMouseExited += args =>
            {
                DockingControl.HighlightedDock = null;
            };

            if (currentDock == dock.Entity)
            {
                selected = true;
                button.Pressed = true;
            }

            button.OnPressed += args =>
            {
                OnDockPress(dock);
            };

            _ourDockButtons[dock.Entity] = button;
            DockPorts.AddChild(button);
        }

        // Button group needs one selected so just show the first one.
        if (!selected)
        {
            // Frontier: press first button in alphabetical order
            // var buttonOne = shuttleDocks[0];
            // OnDockPress(buttonOne);
            OnDockPress(firstState!);
            // End Frontier
        }

    }

    private void OnDockPress(DockingPortState state)
    {
        DockingControl.SetViewedDock(state);
    }
}
