using System.Globalization;
using Content.Client._Mono.Radar;
using Content.Shared._Mono.Radar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Maths;
using Robust.Shared.Timing;

namespace Content.Client.Shuttles.UI;

/// <summary>
/// Shared, read-only combat telemetry for every ship console that uses the
/// authorized radar snapshot belonging to that console.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ShuttleCombatTelemetryPanel : BoxContainer
{
    private const float ReadoutInterval = 0.2f;

    [Dependency] private readonly IEntityManager _entityManager = default!;

    private readonly RadarBlipsSystem _radarBlips;
    private readonly Label[] _hitReportLabels;
    private EntityUid? _consoleEntity;
    private float _readoutAccumulator;

    public ShuttleCombatTelemetryPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _radarBlips = _entityManager.System<RadarBlipsSystem>();
        _hitReportLabels = [HitReport1, HitReport2, HitReport3];
    }

    public void SetConsole(EntityUid? console)
    {
        _consoleEntity = console;
        Visible = console != null;
        _readoutAccumulator = ReadoutInterval;
        UpdateReadout();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_consoleEntity == null)
            return;

        _readoutAccumulator += args.DeltaSeconds;
        if (_readoutAccumulator < ReadoutInterval)
            return;

        _readoutAccumulator = 0f;
        UpdateReadout();
    }

    private void UpdateReadout()
    {
        if (_consoleEntity == null)
        {
            ResetReadout();
            return;
        }

        if (_radarBlips.TryGetOwnshipTelemetry(_consoleEntity, out var telemetry) &&
            RadarCombatTelemetryMath.TryCalculateBrakingDistance(
                telemetry.Velocity.Length(),
                telemetry.BrakeAcceleration,
                out var brakingDistance))
        {
            BrakingDistance.Text = Loc.GetString(
                "shuttle-combat-braking-value",
                ("distance", brakingDistance.ToString("0.0", CultureInfo.InvariantCulture)));
        }
        else
        {
            BrakingDistance.Text = Loc.GetString("shuttle-combat-braking-unavailable");
        }

        var threats = _radarBlips.GetThreatSummary(_consoleEntity);
        if (threats.MissileLockCount > 0)
        {
            ThreatStatus.Text = Loc.GetString(
                "shuttle-combat-threat-lock",
                ("locks", threats.MissileLockCount),
                ("incoming", threats.IncomingCount));
            ThreatStatus.FontColorOverride = Color.FromHex("#FF5864");
        }
        else if (threats.IncomingCount > 0)
        {
            var impactTime = threats.NearestImpactTime is { } time
                ? time.ToString("0.0", CultureInfo.InvariantCulture)
                : "—";
            ThreatStatus.Text = Loc.GetString(
                "shuttle-combat-threat-incoming",
                ("count", threats.IncomingCount),
                ("seconds", impactTime));
            ThreatStatus.FontColorOverride = Color.FromHex("#E6B86A");
        }
        else
        {
            ThreatStatus.Text = Loc.GetString("shuttle-combat-threat-clear");
            ThreatStatus.FontColorOverride = Color.FromHex("#A9E3C7");
        }

        var reports = _radarBlips.GetHitReports(_consoleEntity);
        for (var i = 0; i < _hitReportLabels.Length; i++)
        {
            var label = _hitReportLabels[i];
            if (i >= reports.Count)
            {
                label.Visible = i == 0;
                label.Text = i == 0
                    ? Loc.GetString("shuttle-combat-hit-report-empty")
                    : string.Empty;
                label.ToolTip = null;
                continue;
            }

            var text = FormatHitReport(reports[i]);
            label.Visible = true;
            label.Text = text;
            label.ToolTip = text;
        }
    }

    private void ResetReadout()
    {
        BrakingDistance.Text = Loc.GetString("shuttle-combat-braking-unavailable");
        ThreatStatus.Text = Loc.GetString("shuttle-combat-threat-clear");
        ThreatStatus.FontColorOverride = Color.FromHex("#A9E3C7");

        for (var i = 0; i < _hitReportLabels.Length; i++)
        {
            _hitReportLabels[i].Visible = i == 0;
            _hitReportLabels[i].Text = i == 0
                ? Loc.GetString("shuttle-combat-hit-report-empty")
                : string.Empty;
            _hitReportLabels[i].ToolTip = null;
        }
    }

    internal static string FormatHitReport(ShipHitReportNetData report)
    {
        var section = Loc.GetString(report.Section switch
        {
            ShipHitSection.Bow => "shuttle-combat-section-bow",
            ShipHitSection.Stern => "shuttle-combat-section-stern",
            ShipHitSection.Port => "shuttle-combat-section-port",
            ShipHitSection.Starboard => "shuttle-combat-section-starboard",
            _ => "shuttle-combat-section-bow",
        });
        var result = report.Result switch
        {
            ShipHitResult.Shielded => Loc.GetString("shuttle-combat-result-shielded"),
            ShipHitResult.Destroyed => Loc.GetString("shuttle-combat-result-destroyed"),
            ShipHitResult.Damaged => Loc.GetString(
                "shuttle-combat-result-damaged",
                ("damage", report.Damage.ToString("0", CultureInfo.InvariantCulture))),
            _ => Loc.GetString("shuttle-combat-result-blocked"),
        };
        return Loc.GetString(
            "shuttle-combat-hit-report",
            ("weapon", report.WeaponName),
            ("section", section),
            ("result", result));
    }
}
