using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._NF.Shipyard.BUI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NF.Shipyard.UI;

[GenerateTypedNameReferences]
public sealed partial class ShipyardDockSelectionWindow : FancyWindow
{
    private readonly List<ShipyardGateInfo> _gates = new();
    private NetEntity? _stationGrid;
    private NetEntity? _selectedGate;

    public event Action<NetEntity>? DockConfirmed;

    public ShipyardDockSelectionWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("shipyard-console-call-map-title");
        DockMap.GateSelected += SelectGate;
        CancelButton.OnPressed += _ => Close();
        ConfirmButton.OnPressed += _ => ConfirmSelection();
    }

    public void SetState(
        string shipName,
        NetEntity? stationGrid,
        IReadOnlyList<ShipyardGateInfo> gates,
        NetEntity? selectedGate)
    {
        ShipLabel.Text = Loc.GetString("shipyard-console-call-map-ship", ("ship", shipName));
        _stationGrid = stationGrid;
        _gates.Clear();
        _gates.AddRange(gates);
        var preferredGate = selectedGate ?? _selectedGate;
        _selectedGate = preferredGate is { } selected && _gates.Any(gate => gate.Entity == selected)
            ? preferredGate
            : null;
        DockMap.SetState(_stationGrid, _gates, _selectedGate);
        RefreshSelection();
    }

    private void SelectGate(ShipyardGateInfo gate)
    {
        _selectedGate = gate.Entity;
        DockMap.SetSelectedGate(gate.Entity);
        RefreshSelection();
    }

    private void RefreshSelection()
    {
        var gate = _selectedGate is { } selected
            ? _gates.FirstOrDefault(candidate => candidate.Entity == selected)
            : null;
        if (gate == null)
        {
            SelectedDockLabel.Text = Loc.GetString("shipyard-console-call-map-no-selection");
            ConfirmButton.Disabled = true;
            return;
        }

        SelectedDockLabel.Text = Loc.GetString(
            gate.Available ? "shipyard-console-gate-available" : "shipyard-console-gate-unavailable",
            ("gate", gate.Name));
        ConfirmButton.Disabled = !gate.Available || _stationGrid == null;
    }

    private void ConfirmSelection()
    {
        if (_selectedGate is not { } selected)
            return;

        var gate = _gates.FirstOrDefault(candidate => candidate.Entity == selected);
        if (gate is not { Available: true })
            return;

        DockConfirmed?.Invoke(selected);
        Close();
    }
}
