using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Client._NF.Shipyard.BUI;
using Content.Shared._NF.Bank;
using Content.Shared._NF.Shipyard.BUI;
using Content.Shared._NF.Shipyard.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.GameObjects;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client._NF.Shipyard.UI;

[GenerateTypedNameReferences]
public sealed partial class ShipyardConsoleMenu : FancyWindow
{
    [Dependency] private IPrototypeManager _protoManager = default!;

    public event Action<ButtonEventArgs>? OnSellShip;
    public event Action<string>? OnOrderApproved;
    public event Action<ButtonEventArgs>? OnUnassignDeed;
    public event Action<string>? OnRenameShip;
    public event Action<ButtonEventArgs>? OnParkShip;
    public event Action<Guid, NetEntity>? OnCallShip;
    private readonly ShipyardConsoleBoundUserInterface _menu;
    private readonly List<VesselSize> _categoryStrings = new();
    private readonly List<VesselClass> _classStrings = new();
    private readonly List<VesselEngine> _engineStrings = new();
    private VesselSize? _category;
    private VesselClass? _class;
    private VesselEngine? _engine;

    private List<string> _lastAvailableProtos = new();
    private List<string> _lastUnavailableProtos = new();
    private bool _freeListings = false;
    private bool _validId = false;
    private bool _stateHasCredential;
    private bool _stateAccessGranted;
    private bool _stateMutationInFlight;
    private bool _stateHasStationGrid;
    private bool _stateHasDeed;
    private string _purchaseBlockReason = string.Empty;
    private List<ShipyardGateInfo> _gates = new();
    private List<ShipyardStoredShipInfo> _storedShips = new();
    private NetEntity? _targetCardContext;
    private NetEntity? _stationGrid;
    private NetEntity? _selectedCallGate;
    private ShipyardDockSelectionWindow? _dockSelectionWindow;
    private bool _canCall;

    public bool CanPurchase => _validId;

    public NetEntity? SelectedGate =>
        _gates.Count > 0 && GateSelector.SelectedId >= 0 && GateSelector.SelectedId < _gates.Count
            ? _gates[GateSelector.SelectedId].Entity
            : null;

    public Guid? SelectedStoredShipId =>
        _storedShips.Count > 0 &&
        StoredShipSelector.SelectedId >= 0 &&
        StoredShipSelector.SelectedId < _storedShips.Count
            ? _storedShips[StoredShipSelector.SelectedId].ShipId
            : null;

    public ShipyardConsoleMenu(ShipyardConsoleBoundUserInterface owner)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _menu = owner;
        Title = Loc.GetString("shipyard-console-menu-title");
        ModeTabs.SetTabTitle(0, Loc.GetString("shipyard-console-tab-catalog"));
        ModeTabs.SetTabTitle(1, Loc.GetString("shipyard-console-tab-owned"));
        SearchBar.OnTextChanged += OnSearchBarTextChanged;
        Categories.OnItemSelected += OnCategoryItemSelected;
        Classes.OnItemSelected += OnClassItemSelected;
        Engines.OnItemSelected += OnEngineItemSelected;
        ResetFiltersButton.OnPressed += _ => ResetFilters();
        RenameLineEdit.IsValid = value => value.Length <= 30;
        StoredShipSelector.OnItemSelected += OnStoredShipSelected;
        GateSelector.OnItemSelected += OnGateSelected;
        SellShipButton.OnPressed += (args) => { OnSellShip?.Invoke(args); };
        UnassignDeedButton.OnPressed += (args) => { OnUnassignDeed?.Invoke(args); };
        RenameButton.OnPressed += OnRenameButtonPressed;
        ParkShipButton.OnPressed += args => OnParkShip?.Invoke(args);
        CallShipButton.OnPressed += _ => OpenDockSelection();
        OnClose += CloseDockSelectionWindow;
    }

    private void OnStoredShipSelected(OptionButton.ItemSelectedEventArgs args)
    {
        StoredShipSelector.SelectId(args.Id);
        UpdateCallButton();
        UpdateDockSelectionWindow();
    }

    private void OnGateSelected(OptionButton.ItemSelectedEventArgs args)
    {
        GateSelector.SelectId(args.Id);
        RefreshPurchaseAvailability();
        UpdateCallButton();
    }


    private void OnCategoryItemSelected(OptionButton.ItemSelectedEventArgs args)
    {
        SetCategoryText(args.Id);
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }

    private void OnClassItemSelected(OptionButton.ItemSelectedEventArgs args)
    {
        SetClassText(args.Id);
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }

    private void OnEngineItemSelected(OptionButton.ItemSelectedEventArgs args)
    {
        SetEngineText(args.Id);
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }

    private void OnRenameButtonPressed(ButtonEventArgs args)
    {
        var newName = RenameLineEdit.Text.Trim();
        if (string.IsNullOrEmpty(newName))
            return;

        // Validate length (30 characters max, matching ShuttleDeedComponent.MaxNameLength)
        if (newName.Length > 30)
        {
            newName = newName[..30];
        }

        OnRenameShip?.Invoke(newName);
        RenameLineEdit.Text = "";
    }

    private void OnSearchBarTextChanged(LineEdit.LineEditEventArgs args)
    {
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }

    private void ResetFilters()
    {
        SearchBar.Text = string.Empty;
        _category = null;
        _class = null;
        _engine = null;

        if (_categoryStrings.Count > 0)
            Categories.SelectId(0);
        if (_classStrings.Count > 0)
            Classes.SelectId(0);
        if (_engineStrings.Count > 0)
            Engines.SelectId(0);

        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }

    private void SetCategoryText(int id)
    {
        _category = id == 0 ? null : _categoryStrings[id];
        Categories.SelectId(id);
    }
    private void SetClassText(int id)
    {
        _class = id == 0 ? null : _classStrings[id];
        Classes.SelectId(id);
    }
    private void SetEngineText(int id)
    {
        _engine = id == 0 ? null : _engineStrings[id];
        Engines.SelectId(id);
    }
    /// <summary>
    ///     Populates the list of products that will actually be shown, using the current filters.
    /// </summary>
    public void PopulateProducts(List<string> availablePrototypes, List<string> unavailablePrototypes, bool free, bool canPurchase)
    {
        Vessels.RemoveAllChildren();

        var search = SearchBar.Text.Trim().ToLowerInvariant();

        var newVessels = GetVesselPrototypesFromIds(availablePrototypes);
        var shown = AddVesselsToControls(newVessels, search, free, canPurchase, true);

        var newUnavailableVessels = GetVesselPrototypesFromIds(unavailablePrototypes);
        shown += AddVesselsToControls(newUnavailableVessels, search, free, false, false);

        _lastAvailableProtos = availablePrototypes;
        _lastUnavailableProtos = unavailablePrototypes;
        _freeListings = free;

        EmptyStatePanel.Visible = shown == 0;
        ResultCountLabel.Text = Loc.GetString("shipyard-console-result-count", ("count", shown));
    }

    /// <summary>
    /// Given a set of prototype IDs, returns a corresponding set of prototypes, ordered by name.
    /// </summary>
    private List<VesselPrototype?> GetVesselPrototypesFromIds(IEnumerable<string> protoIds)
    {
        var vesselList = protoIds.Select(it => _protoManager.TryIndex<VesselPrototype>(it, out var proto) ? proto : null)
            .Where(it => it != null)
            .ToList();

        vesselList.Sort((x, y) =>
            string.Compare(x!.Name, y!.Name, StringComparison.CurrentCultureIgnoreCase));
        return vesselList;
    }

    /// <summary>
    /// Adds all vessels in a given list of prototypes as VesselRows in the UI.
    /// </summary>
    private int AddVesselsToControls(
        IEnumerable<VesselPrototype?> vessels,
        string search,
        bool free,
        bool canPurchase,
        bool listingAvailable)
    {
        var shown = 0;
        foreach (var prototype in vessels)
        {
            if (prototype == null)
                continue;

            // Filter any ships
            if (_category != null && !prototype.Category.Equals(_category))
                continue;
            if (_class != null && !prototype.Classes.Contains(_class.Value))
                continue;
            if (_engine != null && !prototype.Engines.Contains(_engine.Value))
                continue;
            if (search.Length > 0 && !prototype.Name.ToLowerInvariant().Contains(search))
                continue;

            string priceText;
            if (free)
                priceText = Loc.GetString("shipyard-console-menu-listing-free");
            else if (!prototype.Purchasable) // Mono
                priceText = Loc.GetString("shipyard-console-menu-listing-voucher");
            else
                priceText = BankSystemExtensions.ToSpesoString(prototype.Price);

            var purchaseAllowed = canPurchase && listingAvailable;
            var availability = listingAvailable
                ? purchaseAllowed
                    ? Loc.GetString("shipyard-console-purchase-ready")
                    : _purchaseBlockReason
                : Loc.GetString("shipyard-console-purchase-blocked-listing");
            var classes = string.Join(", ", prototype.Classes.Select(value =>
                Loc.GetString($"shipyard-console-class-{value}")));
            var engines = string.Join(", ", prototype.Engines.Select(value =>
                Loc.GetString($"shipyard-console-engine-{value}")));

            var vesselEntry = new VesselRow
            {
                Vessel = prototype,
                VesselName = { Text = prototype.Name },
                VesselMeta =
                {
                    Text = Loc.GetString(
                        "shipyard-console-vessel-meta",
                        ("size", Loc.GetString($"shipyard-console-category-{prototype.Category}")),
                        ("classes", classes),
                        ("power", engines)),
                },
                VesselDescription = { Text = prototype.Description }, // Mono
                Availability = { Text = availability },
                Purchase =
                {
                    Text = Loc.GetString("shipyard-console-purchase-available"),
                    ConfirmationText = Loc.GetString(
                        "shipyard-console-confirm-purchase",
                        ("ship", prototype.Name)),
                    Disabled = !purchaseAllowed,
                    ToolTip = purchaseAllowed
                        ? Loc.GetString("shipyard-console-purchase-action-hint")
                        : availability,
                },
                Guidebook = { Disabled = prototype.GuidebookPage is null, TooltipDelay = 0.2f, ToolTip = prototype.Description },
                Price = { Text = priceText },
            };
            vesselEntry.Purchase.OnPressed += _ => OnOrderApproved?.Invoke(prototype.ID);
            Vessels.AddChild(vesselEntry);
            shown++;
        }

        return shown;
    }

    /// <summary>
    ///     Populates the list categories that will actually be shown, using the current filters.
    /// </summary>
    public void PopulateCategories(List<string> availablePrototypes, List<string> unavailablePrototypes)
    {
        _categoryStrings.Clear();
        Categories.Clear();

        AddCategoriesFromPrototypes(availablePrototypes);
        AddCategoriesFromPrototypes(unavailablePrototypes);

        _categoryStrings.Sort();

        // Add "All" category at the top of the list
        _categoryStrings.Insert(0, VesselSize.All);

        foreach (var str in _categoryStrings)
        {
            Categories.AddItem(Loc.GetString($"shipyard-console-category-{str}"));
        }
    }

    /// <summary>
    /// Adds all ship categories from a list of vessel prototypes to the current control's list if they are missing.
    /// </summary>
    private void AddCategoriesFromPrototypes(IEnumerable<string> prototypes)
    {
        foreach (var protoId in prototypes)
        {
            if (!_protoManager.TryIndex<VesselPrototype>(protoId, out var prototype))
                continue;

            if (!_categoryStrings.Contains(prototype.Category) && prototype.Category != VesselSize.All)
            {
                _categoryStrings.Add(prototype.Category);
            }
        }
    }

    /// <summary>
    ///     Populates the list classes that will actually be shown, using the current filters.
    /// </summary>
    public void PopulateClasses(List<string> availablePrototypes, List<string> unavailablePrototypes)
    {
        _classStrings.Clear();
        Classes.Clear();

        AddClassesFromPrototypes(availablePrototypes);
        AddClassesFromPrototypes(unavailablePrototypes);

        _classStrings.Sort();

        // Add "All" category at the top of the list
        _classStrings.Insert(0, VesselClass.All);

        foreach (var str in _classStrings)
        {
            Classes.AddItem(Loc.GetString($"shipyard-console-class-{str}"));
        }
    }

    /// <summary>
    /// Adds all ship classes from a list of vessel prototypes to the current control's list if they are missing.
    /// </summary>
    private void AddClassesFromPrototypes(IEnumerable<string> prototypes)
    {
        foreach (var protoId in prototypes)
        {
            if (!_protoManager.TryIndex<VesselPrototype>(protoId, out var prototype))
                continue;

            foreach (var cl in prototype.Classes)
            {
                if (!_classStrings.Contains(cl) && cl != VesselClass.All)
                {
                    _classStrings.Add(cl);
                }
            }
        }
    }

    /// <summary>
    ///     Populates the list engines that will actually be shown, using the current filters.
    /// </summary>
    public void PopulateEngines(List<string> availablePrototypes, List<string> unavailablePrototypes)
    {
        _engineStrings.Clear();
        Engines.Clear();

        AddEnginesFromPrototypes(availablePrototypes);
        AddEnginesFromPrototypes(unavailablePrototypes);

        _engineStrings.Sort();

        // Add "All" category at the top of the list
        _engineStrings.Insert(0, VesselEngine.All);

        foreach (var str in _engineStrings)
        {
            Engines.AddItem(Loc.GetString($"shipyard-console-engine-{str}"));
        }
    }

    /// <summary>
    /// Adds all ship engine power type from a list of vessel prototypes to the current control's list if they are missing.
    /// </summary>
    private void AddEnginesFromPrototypes(IEnumerable<string> prototypes)
    {
        foreach (var protoId in prototypes)
        {
            if (!_protoManager.TryIndex<VesselPrototype>(protoId, out var prototype))
                continue;

            foreach (var cl in prototype.Engines)
            {
                if (!_engineStrings.Contains(cl) && cl != VesselEngine.All)
                {
                    _engineStrings.Add(cl);
                }
            }
        }
    }

    public void UpdateState(ShipyardConsoleInterfaceState state)
    {
        BalanceLabel.Text = BankSystemExtensions.ToSpesoString(state.Balance);
        ShipyardTitleLabel.Text = Loc.GetString(
            "shipyard-console-terminal-name",
            ("shipyard", state.ShipyardName));
        var shipPrice = 0;
        if (!state.FreeListings)
            shipPrice = state.ShipSellValue;

        var hasShipDeed = state.ShipDeedTitle != null;
        ShipAppraisalLabel.Text = hasShipDeed
            ? $"{BankSystemExtensions.ToSpesoString(shipPrice)} ({state.SellRate * 100.0f:F1}%)"
            : Loc.GetString("shipyard-console-registered-none");
        SellShipButton.Disabled = !state.CanSell;
        UnassignDeedButton.Disabled = !state.CanUnassign;
        SellShipButton.ResetConfirmation();
        UnassignDeedButton.ResetConfirmation();
        SellShipButton.ConfirmationText = state.ShipDeedTitle is { } sellShip
            ? Loc.GetString("shipyard-console-confirm-sell", ("ship", sellShip))
            : Loc.GetString("shipyard-console-confirm-sell-generic");
        UnassignDeedButton.ConfirmationText = state.ShipDeedTitle is { } unassignShip
            ? Loc.GetString("shipyard-console-confirm-unassign-ship", ("ship", unassignShip))
            : Loc.GetString("shipyard-console-confirm-unassign-generic");

        // Show/hide and enable/disable rename controls based on whether there's a ship deed
        RenameContainer.Visible = hasShipDeed;
        RenameLineEdit.Editable = state.CanRename;
        RenameButton.Disabled = !state.CanRename;

        var targetCardChanged = _targetCardContext != state.TargetCard;
        var previouslySelectedShip = targetCardChanged ? null : SelectedStoredShipId;
        _targetCardContext = state.TargetCard;
        _storedShips = state.StoredShips;
        StoredShipSelector.Clear();
        foreach (var stored in _storedShips)
            StoredShipSelector.AddItem(stored.DisplayName);

        var selectedShipIndex = targetCardChanged && state.BoundShipId is { } newCardBoundShip
            ? _storedShips.FindIndex(ship => ship.ShipId == newCardBoundShip)
            : -1;
        if (selectedShipIndex < 0 && previouslySelectedShip is { } previousShip)
            selectedShipIndex = _storedShips.FindIndex(ship => ship.ShipId == previousShip);
        if (selectedShipIndex < 0 && state.BoundShipId is { } boundShip)
            selectedShipIndex = _storedShips.FindIndex(ship => ship.ShipId == boundShip);
        if (selectedShipIndex < 0 && _storedShips.Count > 0)
            selectedShipIndex = 0;
        if (selectedShipIndex >= 0)
            StoredShipSelector.SelectId(selectedShipIndex);
        StoredShipSelector.Disabled = _storedShips.Count == 0 || state.DeedMutationInFlight;
        NoStoredShipsLabel.Visible = _storedShips.Count == 0;

        var previouslySelectedGate = SelectedGate;
        _gates = state.Gates;
        _stationGrid = state.StationGrid;
        if (_selectedCallGate is { } selectedCallGate &&
            !_gates.Any(gate => gate.Entity == selectedCallGate && gate.Available))
        {
            _selectedCallGate = null;
        }

        GateSelector.Clear();
        foreach (var gate in _gates)
            GateSelector.AddItem(Loc.GetString(
                gate.Available ? "shipyard-console-gate-available" : "shipyard-console-gate-unavailable",
                ("gate", gate.Name)));
        if (_gates.Count > 0)
        {
            var selectedIndex = previouslySelectedGate is { } selectedGate
                ? _gates.FindIndex(gate => gate.Entity == selectedGate)
                : -1;
            if (selectedIndex < 0)
                selectedIndex = _gates.FindIndex(gate => gate.Available);
            GateSelector.SelectId(selectedIndex >= 0 ? selectedIndex : 0);
        }

        GateSelector.Disabled = state.DeedMutationInFlight || _gates.Count == 0;
        ParkShipButton.Disabled = !state.CanPark;
        _canCall = state.CanCall && !state.DeedMutationInFlight;
        UpdateCallButton();
        UpdateDockSelectionWindow();

        TargetIdButton.Text = state.IsTargetIdPresent
            ? Loc.GetString("id-card-console-window-eject-button")
            : Loc.GetString("id-card-console-window-insert-button");
        if (state.ShipDeedTitle != null)
        {
            DeedTitle.Text = state.IsForeignDeed
                ? Loc.GetString("shipyard-console-foreign-deed", ("ship", state.ShipDeedTitle))
                : state.ShipDeedTitle;
        }
        else
        {
            DeedTitle.Text = Loc.GetString("shipyard-console-registered-none");
        }

        _stateHasCredential = state.IsTargetIdPresent;
        _stateAccessGranted = state.AccessGranted;
        _stateMutationInFlight = state.DeedMutationInFlight;
        _stateHasStationGrid = state.StationGrid != null;
        _stateHasDeed = hasShipDeed;
        _freeListings = state.FreeListings;
        RefreshHeaderStatus(state);
        RefreshOwnershipStatus(state);
        RefreshPurchaseAvailability();
    }

    private void RefreshHeaderStatus(ShipyardConsoleInterfaceState state)
    {
        CredentialStatusLabel.Text = state.DeedMutationInFlight
            ? Loc.GetString("shipyard-console-credential-processing")
            : !state.IsTargetIdPresent
                ? Loc.GetString("shipyard-console-credential-missing")
                : !state.AccessGranted
                    ? Loc.GetString("shipyard-console-credential-denied")
                    : state.IsForeignDeed
                        ? Loc.GetString("shipyard-console-credential-foreign")
                        : Loc.GetString("shipyard-console-credential-ready");

        var availableGates = _gates.Count(gate => gate.Available);
        GateSummaryLabel.Text = Loc.GetString(
            "shipyard-console-gate-summary",
            ("available", availableGates),
            ("total", _gates.Count));
    }

    private void RefreshOwnershipStatus(ShipyardConsoleInterfaceState state)
    {
        if (state.DeedMutationInFlight)
        {
            OwnershipStatusTitle.Text = Loc.GetString("shipyard-console-status-processing-title");
            OwnershipStatusLabel.Text = Loc.GetString("shipyard-console-status-processing-hint");
        }
        else if (!state.IsTargetIdPresent)
        {
            OwnershipStatusTitle.Text = Loc.GetString("shipyard-console-status-no-card-title");
            OwnershipStatusLabel.Text = Loc.GetString("shipyard-console-status-no-card-hint");
        }
        else if (state.IsForeignDeed)
        {
            OwnershipStatusTitle.Text = Loc.GetString("shipyard-console-status-foreign-title");
            OwnershipStatusLabel.Text = Loc.GetString("shipyard-console-status-foreign-hint");
        }
        else if (state.ShipDeedTitle != null)
        {
            OwnershipStatusTitle.Text = state.ShipParked
                ? Loc.GetString("shipyard-console-status-stored-title")
                : Loc.GetString("shipyard-console-status-active-title");
            OwnershipStatusLabel.Text = state.ShipParked
                ? Loc.GetString("shipyard-console-status-stored-hint")
                : Loc.GetString("shipyard-console-status-active-hint");
        }
        else if (_storedShips.Count > 0)
        {
            OwnershipStatusTitle.Text = Loc.GetString("shipyard-console-status-fleet-title");
            OwnershipStatusLabel.Text = Loc.GetString(
                "shipyard-console-status-fleet-hint",
                ("count", _storedShips.Count));
        }
        else
        {
            OwnershipStatusTitle.Text = Loc.GetString("shipyard-console-status-empty-title");
            OwnershipStatusLabel.Text = Loc.GetString("shipyard-console-status-empty-hint");
        }

        ParkShipButton.ToolTip = state.CanPark
            ? Loc.GetString("shipyard-console-park-action-hint")
            : state.IsForeignDeed
                ? Loc.GetString("shipyard-console-owner-denied")
                : state.DeedMutationInFlight
                    ? Loc.GetString("shipyard-console-status-processing-hint")
                    : Loc.GetString("shipyard-console-park-disabled-hint");

        CallShipHint.Text = GetCallShipHint(state);
        CallShipButton.ToolTip = CallShipHint.Text;
        DangerHintLabel.Text = state.ShipDeedTitle is { } shipName
            ? Loc.GetString("shipyard-console-danger-zone-ship-hint", ("ship", shipName))
            : Loc.GetString("shipyard-console-danger-zone-hint");
    }

    private string GetCallShipHint(ShipyardConsoleInterfaceState state)
    {
        if (state.DeedMutationInFlight)
            return Loc.GetString("shipyard-console-status-processing-hint");
        if (!state.IsTargetIdPresent)
            return Loc.GetString("shipyard-console-call-disabled-no-id");
        if (state.IsForeignDeed)
            return Loc.GetString("shipyard-console-owner-denied");
        if (_storedShips.Count == 0)
            return Loc.GetString("shipyard-console-call-disabled-no-ships");
        if (_stationGrid == null)
            return Loc.GetString("shipyard-console-call-disabled-no-link");
        if (!_gates.Any(gate => gate.Available))
            return Loc.GetString("shipyard-console-call-disabled-no-gate");
        if (!state.CanCall)
            return Loc.GetString("shipyard-console-call-disabled-active-deed");

        return Loc.GetString("shipyard-console-call-action-hint");
    }

    private void RefreshPurchaseAvailability()
    {
        var selectedGate = GetSelectedGateInfo();
        _validId = _stateHasCredential &&
                   _stateAccessGranted &&
                   !_stateMutationInFlight &&
                   !_stateHasDeed &&
                   _stateHasStationGrid &&
                   selectedGate is { Available: true };

        _purchaseBlockReason = _stateMutationInFlight
            ? Loc.GetString("shipyard-console-purchase-blocked-processing")
            : !_stateHasCredential
                ? Loc.GetString("shipyard-console-purchase-blocked-no-id")
                : !_stateAccessGranted
                    ? Loc.GetString("shipyard-console-purchase-blocked-access")
                    : _stateHasDeed
                        ? Loc.GetString("shipyard-console-purchase-blocked-existing-deed")
                        : !_stateHasStationGrid
                            ? Loc.GetString("shipyard-console-purchase-blocked-no-link")
                            : !_gates.Any(gate => gate.Available)
                                ? Loc.GetString("shipyard-console-purchase-blocked-no-gate")
                                : selectedGate is not { Available: true }
                                    ? Loc.GetString("shipyard-console-purchase-blocked-selected-gate")
                                    : Loc.GetString("shipyard-console-purchase-ready");

        PurchaseStatusTitle.Text = Loc.GetString(
            _validId
                ? "shipyard-console-procurement-ready-title"
                : "shipyard-console-procurement-locked-title");
        PurchaseStatusLabel.Text = _purchaseBlockReason;
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }

    private ShipyardGateInfo? GetSelectedGateInfo()
    {
        return GateSelector.SelectedId >= 0 && GateSelector.SelectedId < _gates.Count
            ? _gates[GateSelector.SelectedId]
            : null;
    }

    private void UpdateCallButton()
    {
        CallShipButton.Disabled = !_canCall ||
                                  SelectedStoredShipId == null ||
                                  _stationGrid == null ||
                                  !_gates.Any(gate => gate.Available);
    }

    private void OpenDockSelection()
    {
        if (!_canCall ||
            _stationGrid == null ||
            SelectedStoredShipId is not { } shipId ||
            _storedShips.FirstOrDefault(ship => ship.ShipId == shipId) is not { } ship)
        {
            return;
        }

        CloseDockSelectionWindow();
        var window = new ShipyardDockSelectionWindow();
        _dockSelectionWindow = window;
        window.SetState(ship.DisplayName, _stationGrid, _gates, _selectedCallGate);
        window.DockConfirmed += gate =>
        {
            if (!_canCall || SelectedStoredShipId != shipId)
                return;

            _selectedCallGate = gate;
            OnCallShip?.Invoke(shipId, gate);
        };
        window.OnClose += () =>
        {
            if (_dockSelectionWindow == window)
                _dockSelectionWindow = null;
        };
        window.OpenCentered();
    }

    private void UpdateDockSelectionWindow()
    {
        if (_dockSelectionWindow == null)
            return;

        if (!_canCall ||
            _stationGrid == null ||
            SelectedStoredShipId is not { } shipId ||
            _storedShips.FirstOrDefault(ship => ship.ShipId == shipId) is not { } ship)
        {
            CloseDockSelectionWindow();
            return;
        }

        _dockSelectionWindow.SetState(ship.DisplayName, _stationGrid, _gates, _selectedCallGate);
    }

    private void CloseDockSelectionWindow()
    {
        _dockSelectionWindow?.Close();
        _dockSelectionWindow = null;
    }
}
