using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class LogProbeUiFragment : BoxContainer
{
    /// <summary>
    /// Action invoked when the print button gets pressed.
    /// </summary>
    public Action? OnPrintPressed;

    public LogProbeUiFragment()
    {
        RobustXamlLoader.Load(this);

        PrintButton.OnPressed += _ => OnPrintPressed?.Invoke();
    }

    public void UpdateState(string name, List<PulledAccessLog> logs)
    {
        var hasDevice = !string.IsNullOrWhiteSpace(name);
        EntityName.Text = hasDevice
            ? Loc.GetString("log-probe-printout-device", ("name", name))
            : Loc.GetString("log-probe-no-device");
        EntityName.ToolTip = EntityName.Text;
        PrintButton.Disabled = !hasDevice;

        ProbedDeviceContainer.RemoveAllChildren();
        EmptyLabel.Text = hasDevice
            ? Loc.GetString("log-probe-empty")
            : Loc.GetString("log-probe-no-device");
        EmptyLabel.Visible = logs.Count == 0;
        if (EmptyLabel.Visible)
            ProbedDeviceContainer.AddChild(EmptyLabel);

        var count = 1;
        foreach (var log in logs)
        {
            AddAccessLog(log, count);
            count++;
        }
    }

    private void AddAccessLog(PulledAccessLog log, int numberLabelText)
    {
        var timeLabelText = TimeSpan.FromSeconds(Math.Truncate(log.Time.TotalSeconds)).ToString();
        var accessorLabelText = log.Accessor;
        var entry = new LogProbeUiEntry(numberLabelText, timeLabelText, accessorLabelText);

        ProbedDeviceContainer.AddChild(entry);
    }
}
