using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NetProbeUiFragment : BoxContainer
{
    public NetProbeUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;
    }

    public void UpdateState(List<ProbedNetworkDevice> devices)
    {
        ProbedDeviceContainer.RemoveAllChildren();
        EmptyLabel.Visible = devices.Count == 0;
        if (EmptyLabel.Visible)
            ProbedDeviceContainer.AddChild(EmptyLabel);

        // Display the newest scan first without mutating the state-owned list.
        for (var i = devices.Count - 1; i >= 0; i--)
            AddProbedDevice(devices[i]);
    }

    private void AddProbedDevice(ProbedNetworkDevice device)
    {
        var card = new PanelContainer
        {
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 5),
            StyleClasses = { "PdaListingCard" },
        };
        var row = new BoxContainer
        {
            HorizontalExpand = true,
            Orientation = LayoutOrientation.Horizontal,
            Margin = new Thickness(8, 6),
            SeparationOverride = 8,
        };

        row.AddChild(MakeCell(device.Name, 2));
        row.AddChild(MakeCell(device.Address, 2));
        row.AddChild(MakeCell(device.Frequency, 1));
        row.AddChild(MakeCell(device.NetId, 2));

        card.AddChild(row);
        ProbedDeviceContainer.AddChild(card);
    }

    private static Label MakeCell(string text, float ratio)
    {
        return new Label
        {
            Text = text,
            ToolTip = text,
            HorizontalExpand = true,
            ClipText = true,
            SizeFlagsStretchRatio = ratio,
        };
    }
}
