using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NotekeeperUiFragment : BoxContainer
{

    public event Action<string>? OnNoteAdded;
    public event Action<string>? OnNoteRemoved;

    public NotekeeperUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        Input.OnTextEntered += _ =>
        {
            var note = Input.Text.Trim();
            if (string.IsNullOrWhiteSpace(note))
                return;

            AddNote(note);
            OnNoteAdded?.Invoke(note);
            Input.Clear();
        };

        UpdateState(new List<string>());
    }

    public void UpdateState(List<string> notes)
    {
        MessageContainer.RemoveAllChildren();
        EmptyLabel.Visible = notes.Count == 0;
        if (EmptyLabel.Visible)
            MessageContainer.AddChild(EmptyLabel);

        foreach (var note in notes)
        {
           AddNote(note);
        }
    }

    private void AddNote(string note)
    {
        EmptyLabel.Visible = false;
        if (EmptyLabel.Parent == MessageContainer)
            MessageContainer.RemoveChild(EmptyLabel);

        var card = new PanelContainer
        {
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 6),
            StyleClasses = { "PdaListingCard" },
        };
        var row = new BoxContainer
        {
            HorizontalExpand = true,
            Orientation = LayoutOrientation.Horizontal,
            Margin = new Thickness(8, 6),
        };

        var label = new Label
        {
            Text = note,
            ToolTip = note,
            HorizontalExpand = true,
            ClipText = true,
        };

        var removeButton = new TextureButton
        {
            ToolTip = Loc.GetString("notekeeper-remove"),
        };
        removeButton.AddStyleClass("windowCloseButton");
        removeButton.OnPressed += _ => OnNoteRemoved?.Invoke(label.Text);

        row.AddChild(label);
        row.AddChild(removeButton);
        card.AddChild(row);
        MessageContainer.AddChild(card);
    }
}
