using Content.Client.UserInterface.Controls;
using Content.Shared._LuaM.Stargate;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using System.Linq;
using System.Numerics;

namespace Content.Client._LuaM.Stargate;

[GenerateTypedNameReferences]
public sealed partial class LuaMStargateAddressEditorWindow : FancyWindow
{
    public event Action<byte>? SymbolPressed;
    public event Action? ClearPressed;
    public event Action? SaveLeftPressed;
    public event Action? SaveRightPressed;
    public event Action<int>? DeleteLeftPressed;
    public event Action<int>? DeleteRightPressed;
    public event Action<int>? MoveLeftToRightPressed;
    public event Action<int>? MoveRightToLeftPressed;
    public event Action<int>? CopyLeftToRightPressed;
    public event Action<int>? CopyRightToLeftPressed;
    public event Action? CloneLeftToRightPressed;
    public event Action? CloneRightToLeftPressed;

    private const float RingRadius = 165f;
    private const float ButtonSize = 28f;
    private const float RingSize = 420f;

    private static readonly Color GlyphNormal = Color.FromHex("#D4C5A0");
    private static readonly Color GlyphHover = Color.FromHex("#3FB2FF");
    private static readonly Color GlyphDisabled = Color.FromHex("#555555");
    private static readonly Color GlyphActive = Color.FromHex("#1C5CFF");

    private readonly Font _glyphFont;
    private readonly Font _smallGlyphFont;
    private readonly Dictionary<byte, (ContainerButton Button, Label Label)> _symbolButtons = new();

    private byte _maxSymbols = LuaMStargateGlyphs.Count;
    private int _addressLength = 6;
    private byte[] _currentInput = Array.Empty<byte>();
    private byte[][]? _leftAddresses;
    private byte[][]? _rightAddresses;

    public LuaMStargateAddressEditorWindow()
    {
        RobustXamlLoader.Load(this);

        var cache = IoCManager.Resolve<IResourceCache>();
        var resource = cache.GetResource<FontResource>("/Fonts/StarGate/stargatesg1addressglyphs.ttf");
        _glyphFont = new VectorFont(resource, 20);
        _smallGlyphFont = new VectorFont(resource, 15);
        AddressDisplay.FontOverride = _glyphFont;

        ClearButton.OnPressed += _ => ClearPressed?.Invoke();
        SaveLeftButton.OnPressed += _ => SaveLeftPressed?.Invoke();
        SaveRightButton.OnPressed += _ => SaveRightPressed?.Invoke();

        RebuildGlyphRing();
        Refresh();
    }

    public void UpdateState(LuaMStargateAddressEditorUiState state)
    {
        _currentInput = state.CurrentInput;
        _addressLength = state.AddressLength;
        _leftAddresses = state.LeftDiskAddresses;
        _rightAddresses = state.RightDiskAddresses;

        if (_maxSymbols != state.MaxSymbols)
        {
            _maxSymbols = state.MaxSymbols;
            RebuildGlyphRing();
        }

        Refresh();
    }

    private void RebuildGlyphRing()
    {
        foreach (var entry in _symbolButtons.Values)
            GlyphRing.RemoveChild(entry.Button);
        _symbolButtons.Clear();

        var center = RingSize / 2f;
        var transparent = new StyleBoxFlat(Color.Transparent);
        for (byte symbol = 1; symbol <= _maxSymbols; symbol++)
        {
            var captured = symbol;
            var label = new Label
            {
                Text = LuaMStargateGlyphs.GetChar(symbol).ToString(),
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                FontColorOverride = GlyphNormal,
                FontOverride = _glyphFont,
            };
            var button = new ContainerButton
            {
                MinSize = new Vector2(ButtonSize, ButtonSize),
                MaxSize = new Vector2(ButtonSize, ButtonSize),
                StyleBoxOverride = transparent,
            };
            button.AddChild(label);
            button.OnPressed += _ => SymbolPressed?.Invoke(captured);
            button.OnMouseEntered += _ =>
            {
                if (!button.Disabled)
                    label.FontColorOverride = GlyphHover;
            };
            button.OnMouseExited += _ =>
            {
                if (!button.Disabled)
                    label.FontColorOverride = _currentInput.Contains(captured) ? GlyphActive : GlyphNormal;
            };

            _symbolButtons[captured] = (button, label);
            GlyphRing.AddChild(button);

            var angle = 2d * Math.PI * (symbol - 1) / _maxSymbols - Math.PI / 2d;
            var position = new Vector2(
                center + RingRadius * (float) Math.Cos(angle) - ButtonSize / 2f,
                center + RingRadius * (float) Math.Sin(angle) - ButtonSize / 2f);
            LayoutContainer.SetPosition(button, position);
        }
    }

    private void Refresh()
    {
        var symbols = _currentInput
            .Select(LuaMStargateGlyphs.GetChar)
            .Select(character => character.ToString())
            .ToList();
        while (symbols.Count < _addressLength)
            symbols.Add("_");
        AddressDisplay.Text = string.Join(" ", symbols);

        var inputFull = _currentInput.Length >= _addressLength;
        foreach (var (symbol, entry) in _symbolButtons)
        {
            var used = _currentInput.Contains(symbol);
            entry.Button.Disabled = inputFull || used;
            entry.Label.FontColorOverride = used
                ? GlyphActive
                : inputFull
                    ? GlyphDisabled
                    : GlyphNormal;
        }

        SaveLeftButton.Disabled = _leftAddresses == null || _currentInput.Length != _addressLength;
        SaveRightButton.Disabled = _rightAddresses == null || _currentInput.Length != _addressLength;
        RebuildDiskLists();
    }

    private void RebuildDiskLists()
    {
        LeftAddressList.RemoveAllChildren();
        RightAddressList.RemoveAllChildren();

        if (_leftAddresses == null)
            LeftAddressList.AddChild(new Label
            {
                Text = Loc.GetString("stargate-editor-no-disk"),
                HorizontalAlignment = HAlignment.Center,
            });
        else
            PopulateDiskList(LeftAddressList, _leftAddresses, isRight: false);

        if (_rightAddresses == null)
            RightAddressList.AddChild(new Label
            {
                Text = Loc.GetString("stargate-editor-no-disk"),
                HorizontalAlignment = HAlignment.Center,
            });
        else
            PopulateDiskList(RightAddressList, _rightAddresses, isRight: true);
    }

    private void PopulateDiskList(BoxContainer list, byte[][] addresses, bool isRight)
    {
        if (addresses.Length > 0)
        {
            var clone = new Button
            {
                Text = Loc.GetString(isRight
                    ? "stargate-editor-clone-to-left"
                    : "stargate-editor-clone-to-right"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 4),
                Disabled = isRight ? _leftAddresses == null : _rightAddresses == null,
            };
            clone.OnPressed += _ =>
            {
                if (isRight)
                    CloneRightToLeftPressed?.Invoke();
                else
                    CloneLeftToRightPressed?.Invoke();
            };
            list.AddChild(clone);
        }

        for (var index = 0; index < addresses.Length; index++)
            list.AddChild(CreateAddressRow(addresses[index], isRight, index));
    }

    private BoxContainer CreateAddressRow(byte[] address, bool isRight, int index)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 2),
        };
        var label = new Label
        {
            Text = string.Join(" ", address.Select(LuaMStargateGlyphs.GetChar)),
            FontOverride = _smallGlyphFont,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
            MinWidth = 100,
        };
        row.AddChild(label);

        var otherDiskPresent = isRight ? _leftAddresses != null : _rightAddresses != null;
        var move = new Button
        {
            Text = isRight ? "←" : "→",
            ToolTip = Loc.GetString("stargate-editor-move"),
            MinWidth = 30,
            Margin = new Thickness(2, 0),
            Disabled = !otherDiskPresent,
        };
        move.OnPressed += _ =>
        {
            if (isRight)
                MoveRightToLeftPressed?.Invoke(index);
            else
                MoveLeftToRightPressed?.Invoke(index);
        };
        row.AddChild(move);

        var copy = new Button
        {
            Text = isRight ? "⇐" : "⇒",
            ToolTip = Loc.GetString("stargate-editor-copy"),
            MinWidth = 30,
            Margin = new Thickness(2, 0),
            Disabled = !otherDiskPresent,
        };
        copy.OnPressed += _ =>
        {
            if (isRight)
                CopyRightToLeftPressed?.Invoke(index);
            else
                CopyLeftToRightPressed?.Invoke(index);
        };
        row.AddChild(copy);

        var delete = new Button
        {
            Text = "×",
            ToolTip = Loc.GetString("stargate-editor-delete"),
            MinWidth = 28,
            Margin = new Thickness(2, 0),
        };
        delete.OnPressed += _ =>
        {
            if (isRight)
                DeleteRightPressed?.Invoke(index);
            else
                DeleteLeftPressed?.Invoke(index);
        };
        row.AddChild(delete);
        return row;
    }
}
