using Content.Client.UserInterface.Controls;
using Content.Shared._LuaM.Stargate;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using System.Linq;
using System.Numerics;

namespace Content.Client._LuaM.Stargate;

[GenerateTypedNameReferences]
public sealed partial class LuaMStargateConsoleWindow : FancyWindow
{
    public event Action<byte>? SymbolPressed;
    public event Action? DialPressed;
    public event Action? ClearPressed;
    public event Action? ClosePressed;
    public event Action? SaveAddressPressed;
    public event Action<byte[]>? DiskAddressDialPressed;
    public event Action<int>? DiskAddressDeletePressed;
    public event Action? IrisTogglePressed;

    private const float RingRadius = 210f;
    private const float GlyphButtonSize = 30f;
    private const float DialButtonSize = 70f;
    private const float RingSize = 490f;

    private static readonly Color GlyphNormal = Color.FromHex("#D4C5A0");
    private static readonly Color GlyphHover = Color.FromHex("#3FB2FF");
    private static readonly Color GlyphDisabled = Color.FromHex("#555555");
    private static readonly Color GlyphActive = Color.FromHex("#1C5CFF");

    [Dependency] private readonly IClipboardManager _clipboard = default!;

    private readonly Font _glyphFont;
    private readonly Font _smallGlyphFont;
    private readonly Dictionary<byte, (ContainerButton Button, Label Label)> _glyphButtons = new();

    private Button _dialButton = default!;
    private byte[] _currentInput = Array.Empty<byte>();
    private byte[] _gateAddress = Array.Empty<byte>();
    private int _addressLength = 6;
    private bool _portalOpen;
    private bool _dialing;

    public LuaMStargateConsoleWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        var cache = IoCManager.Resolve<IResourceCache>();
        var resource = cache.GetResource<FontResource>("/Fonts/StarGate/stargatesg1addressglyphs.ttf");
        _glyphFont = new VectorFont(resource, 20);
        _smallGlyphFont = new VectorFont(resource, 16);
        AddressDisplay.FontOverride = _smallGlyphFont;
        GateAddressLabel.FontOverride = _glyphFont;

        CreateDialButton();
        BuildGlyphRing();

        ClearButton.OnPressed += _ => ClearPressed?.Invoke();
        PortalCloseButton.OnPressed += _ => ClosePressed?.Invoke();
        SaveAddressButton.OnPressed += _ => SaveAddressPressed?.Invoke();
        IrisToggleButton.OnPressed += _ => IrisTogglePressed?.Invoke();
        CopyAddressButton.OnPressed += _ => CopyGateAddress();
    }

    public void UpdateState(LuaMStargateConsoleUiState state)
    {
        _currentInput = state.CurrentInput;
        _gateAddress = state.GateAddress;
        _addressLength = state.AddressLength;
        _portalOpen = state.PortalOpen;
        _dialing = state.Dialing;

        StatusLabel.Text = Loc.GetString(state.Status);
        AddressDisplay.Text = FormatAddress(_currentInput, _addressLength, " - ");
        UpdateGateAddressDisplay();
        UpdateButtons();
        UpdateDisk(state.DiskAddresses);

        IrisToggleButton.Visible = state.HasControllable;
        IrisToggleButton.Disabled = !state.HasControllable || state.IrisBusy;
        IrisToggleButton.Text = Loc.GetString(state.IrisOpen
            ? "stargate-console-close-iris"
            : "stargate-console-open-iris");
    }

    private void CreateDialButton()
    {
        _dialButton = new Button
        {
            Text = Loc.GetString("stargate-console-dial"),
            MinSize = new Vector2(DialButtonSize, DialButtonSize),
            MaxSize = new Vector2(DialButtonSize, DialButtonSize),
        };
        _dialButton.OnPressed += _ => DialPressed?.Invoke();
        DhdRingContainer.AddChild(_dialButton);

        var center = RingSize / 2f;
        LayoutContainer.SetPosition(
            _dialButton,
            new Vector2(center - DialButtonSize / 2f, center - DialButtonSize / 2f));
    }

    private void BuildGlyphRing()
    {
        var center = RingSize / 2f;
        var transparent = new StyleBoxFlat(Color.Transparent);

        for (byte symbol = 1; symbol <= LuaMStargateGlyphs.Count; symbol++)
        {
            var captured = symbol;
            var label = new Label
            {
                Text = LuaMStargateGlyphs.GetChar(symbol).ToString(),
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                FontColorOverride = GlyphNormal,
                FontOverride = _glyphFont,
            };
            var button = new ContainerButton
            {
                MinSize = new Vector2(GlyphButtonSize, GlyphButtonSize),
                MaxSize = new Vector2(GlyphButtonSize, GlyphButtonSize),
                StyleBoxOverride = transparent,
                ToolTip = Loc.GetString("stargate-console-symbol-tooltip", ("number", symbol)),
            };
            button.AddChild(label);
            button.OnPressed += _ => SymbolPressed?.Invoke(captured);
            button.OnMouseEntered += _ =>
            {
                if (!button.Disabled)
                    label.FontColorOverride = GlyphHover;
            };
            button.OnMouseExited += _ =>
            {
                if (!button.Disabled)
                    label.FontColorOverride = _currentInput.Contains(captured) ? GlyphActive : GlyphNormal;
            };

            _glyphButtons[captured] = (button, label);
            DhdRingContainer.AddChild(button);

            var angle = 2d * Math.PI * (symbol - 1) / LuaMStargateGlyphs.Count - Math.PI / 2d;
            var position = new Vector2(
                center + RingRadius * (float) Math.Cos(angle) - GlyphButtonSize / 2f,
                center + RingRadius * (float) Math.Sin(angle) - GlyphButtonSize / 2f);
            LayoutContainer.SetPosition(button, position);
        }
    }

    private void UpdateGateAddressDisplay()
    {
        var hasAddress = _gateAddress.Length > 0;
        GateAddressTitleLabel.Visible = hasAddress;
        GateAddressLabel.Visible = hasAddress;
        CopyAddressButton.Visible = hasAddress;
        GateAddressLabel.Text = hasAddress
            ? FormatAddress(_gateAddress, _gateAddress.Length, " ")
            : string.Empty;
    }

    private void UpdateButtons()
    {
        var interactionLocked = _portalOpen || _dialing;
        var inputFull = _currentInput.Length >= _addressLength;

        _dialButton.Disabled = interactionLocked || _currentInput.Length != _addressLength;
        ClearButton.Disabled = interactionLocked;
        PortalCloseButton.Disabled = !_portalOpen && !_dialing;
        PortalCloseButton.Visible = _portalOpen || _dialing;

        foreach (var (symbol, entry) in _glyphButtons)
        {
            var used = _currentInput.Contains(symbol);
            entry.Button.Disabled = interactionLocked || inputFull || used;
            entry.Label.FontColorOverride = used
                ? GlyphActive
                : entry.Button.Disabled
                    ? GlyphDisabled
                    : GlyphNormal;
        }
    }

    private void UpdateDisk(byte[][]? addresses)
    {
        DiskPanel.Visible = addresses != null;
        DiskAddressList.RemoveAllChildren();

        var interactionLocked = _portalOpen || _dialing;
        SaveAddressButton.Disabled = addresses == null || interactionLocked || _gateAddress.Length == 0;
        if (addresses == null)
            return;

        for (var index = 0; index < addresses.Length; index++)
        {
            var capturedIndex = index;
            var capturedAddress = addresses[index].ToArray();
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 2),
            };
            var label = new Label
            {
                Text = string.Join(' ', capturedAddress.Select(LuaMStargateGlyphs.GetChar)),
                FontOverride = _smallGlyphFont,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
            };
            var dial = new Button
            {
                Text = Loc.GetString("stargate-console-disk-dial"),
                Margin = new Thickness(2, 0),
                Disabled = interactionLocked,
            };
            var delete = new Button
            {
                Text = "X",
                MinWidth = 30,
                Margin = new Thickness(2, 0),
                Disabled = interactionLocked,
            };
            dial.OnPressed += _ => DiskAddressDialPressed?.Invoke(capturedAddress);
            delete.OnPressed += _ => DiskAddressDeletePressed?.Invoke(capturedIndex);
            row.AddChild(label);
            row.AddChild(dial);
            row.AddChild(delete);
            DiskAddressList.AddChild(row);
        }
    }

    private void CopyGateAddress()
    {
        if (_gateAddress.Length == 0)
            return;

        var glyphs = _gateAddress.Select(LuaMStargateGlyphs.GetChar);
        var markup = $"[stargate size=20]{string.Join(' ', glyphs)}[/stargate]";
        _clipboard.SetText(markup);
    }

    private static string FormatAddress(IReadOnlyList<byte> address, int length, string separator)
    {
        var symbols = address.Select(LuaMStargateGlyphs.GetChar).Select(character => character.ToString()).ToList();
        while (symbols.Count < length)
            symbols.Add("_");
        return string.Join(separator, symbols);
    }
}
