using Content.Client._LuaM.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Tabs.AdminTab
{
    [GenerateTypedNameReferences]
    public sealed partial class AdminTab : Control
    {
        [Dependency] private readonly IEntityManager _entities = default!;

        public AdminTab()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            LuaMAiDirectorButton.OnPressed += _ => _entities.System<LuaMAiDirectorOpenSystem>().RequestOpen();
            LuaMAiDirectorButton.ToolTip = Loc.GetString("admin-player-actions-window-luam-ai-director-tooltip");
        }
    }
}
