using Content.Shared._NF.Bank;
using Content.Shared._NF.BountyContracts;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;

namespace Content.Client._NF.BountyContracts.UI;

[GenerateTypedNameReferences]
public sealed partial class BountyContractUiFragmentListEntry : Control
{
    public event Action<BountyContract>? OnRemoveButtonPressed;
    public event Action<BountyContract, bool>? OnSetAcceptedButtonPressed;

    public BountyContractUiFragmentListEntry(BountyContract contract, bool canRemoveContracts, NetEntity loaderUid)
    {
        RobustXamlLoader.Load(this);

        BountyName.Text = contract.Name;

        // vessel
        if (string.IsNullOrEmpty(contract.Vessel) || contract.Vessel == Loc.GetString("bounty-contracts-ui-create-vessel-unknown"))
            BountyVessel.Visible = false;
        else
            BountyVessel.Text = Loc.GetString("bounty-contracts-ui-list-vessel", ("vessel", contract.Vessel));

        BountyRouteHint.Text = SharedBountyContractSystem.BuildRouteHintForUi(contract.Description, contract.Vessel);

        // bounty description
        if (string.IsNullOrWhiteSpace(contract.Description))
            BountyDescription.Visible = false;
        else
            BountyDescription.SetMessage(contract.Description);

        // author
        string author = contract.Author ?? "";
        if (string.IsNullOrWhiteSpace(contract.Author))
            author = Loc.GetString("bounty-contracts-ui-list-unknown-author");

        BountyAuthor.Text = Loc.GetString("bounty-contracts-ui-list-author", ("author", author));
        var isAccepted = contract.AcceptedByUid != NetEntity.Invalid;
        var acceptedByThisLoader = isAccepted && contract.AcceptedByUid == loaderUid;
        var acceptedBy = string.IsNullOrWhiteSpace(contract.AcceptedBy)
            ? Loc.GetString("bounty-contracts-ui-list-unknown-author")
            : contract.AcceptedBy;

        BountyAccepted.Text = isAccepted
            ? Loc.GetString("bounty-contracts-ui-list-accepted-by", ("name", acceptedBy))
            : Loc.GetString("bounty-contracts-ui-list-unaccepted");

        // bounty reward
        BountyReward.Text = BankSystemExtensions.ToSpesoString(contract.Reward);

        // accept button
        AcceptButton.Text = acceptedByThisLoader
            ? Loc.GetString("bounty-contracts-ui-list-release")
            : isAccepted
                ? Loc.GetString("bounty-contracts-ui-list-accepted")
                : Loc.GetString("bounty-contracts-ui-list-accept");
        AcceptButton.ToolTip = acceptedByThisLoader
            ? Loc.GetString("bounty-contracts-ui-list-release-tooltip")
            : isAccepted
                ? Loc.GetString("bounty-contracts-ui-list-accepted-tooltip", ("name", acceptedBy))
                : Loc.GetString("bounty-contracts-ui-list-accept-tooltip");
        AcceptButton.Disabled = isAccepted && !acceptedByThisLoader;
        AcceptButton.OnPressed += _ => OnSetAcceptedButtonPressed?.Invoke(contract, !acceptedByThisLoader);

        // remove button
        RemoveButton.OnPressed += _ => OnRemoveButtonPressed?.Invoke(contract);
        RemoveButton.Disabled = !canRemoveContracts;
        RemoveButton.ToolTip = canRemoveContracts
            ? Loc.GetString("bounty-contracts-ui-list-remove-tooltip")
            : Loc.GetString("bounty-contracts-ui-list-remove-disabled-tooltip");

        // Get category
        var meta = SharedBountyContractSystem.CategoriesMeta[contract.Category];
        BountyPanel.ModulateSelfOverride = meta.UiColor;

        var category = Loc.GetString("bounty-contracts-ui-list-category", ("category", Loc.GetString(meta.Name))); 
        BountyCategory.Text = category;
    }
}
