using System.Globalization;
using System.Linq;
using Content.Client.GameTicking.Managers;
using Content.Shared.PDA;
using Robust.Shared.Utility;
using Content.Shared.CartridgeLoader;
using Content.Client.Message;
using Content.Shared._NF.Bank;
using Robust.Client.UserInterface;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Timing;

namespace Content.Client.PDA
{
    [GenerateTypedNameReferences]
    public sealed partial class PdaMenu : PdaWindow
    {
        [Dependency] private IClipboardManager _clipboard = null!;
        [Dependency] private IGameTiming _gameTiming = default!;
        [Dependency] private IEntitySystemManager _entitySystem = default!;
        private readonly ClientGameTicker _gameTicker;

        public const int HomeView = 0;
        public const int ServicesView = 1;
        public const int ProgramListView = 2;
        public const int SettingsView = 3;
        public const int ProgramContentView = 4;


        private string _pdaOwner = Loc.GetString("comp-pda-ui-unknown");
        private string _owner = Loc.GetString("comp-pda-ui-unknown");
        private string _jobTitle = Loc.GetString("comp-pda-ui-unassigned");
        private string _stationName = Loc.GetString("comp-pda-ui-unknown");
        private string _alertLevel = Loc.GetString("comp-pda-ui-unknown");
        private string _instructions = Loc.GetString("comp-pda-ui-unknown");

        private string _balance = Loc.GetString("comp-pda-ui-unknown"); // Frontier
        private string _bankAccountId = Loc.GetString("comp-pda-ui-unknown"); // Frontier
        private string _shuttleDeed = Loc.GetString("comp-pda-ui-unknown"); // Frontier
        private string _donationShopInfo = Loc.GetString("comp-pda-ui-unknown"); // LuaM
        private PdaBankTransferConfirmation? _bankTransferConfirmation; // LuaM
        private PdaBankTransferRecovery? _bankTransferRecovery; // LuaM
        private const string DonationCurrencyCode = "LC"; // LuaM

        private int _currentView;
        private long _lastDisplayedStationSecond = -1;

        public event Action<EntityUid>? OnProgramItemPressed;
        public event Action<EntityUid>? OnUninstallButtonPressed;
        public event Action<EntityUid>? OnInstallButtonPressed;
        public event Action<string, int>? OnBankTransferPreviewPressed; // LuaM
        public event Action<Guid>? OnBankTransferPressed; // LuaM
        public event Action<Guid>? OnBankTransferCancelPressed; // LuaM
        public event Action<Guid>? OnBankTransferAcknowledgePressed; // LuaM
        public event Action<string>? OnDonationShopPurchasePressed; // LuaM
        public PdaMenu()
        {
            IoCManager.InjectDependencies(this);
            _gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>();
            RobustXamlLoader.Load(this);

            // Reapply localized text after nested custom controls have loaded their own XAML.
            // Depending on XAML construction order, assigning these custom properties only in
            // the parent markup can leave their inner labels empty in the live PDA window.
            ProgramListButton.LabelText = Loc.GetString("comp-pda-io-program-list-button");
            ServicesButton.LabelText = Loc.GetString("comp-pda-io-services-button");
            SettingsButton.LabelText = Loc.GetString("comp-pda-io-settings-button");
            AccessRingtoneButton.Text = Loc.GetString("comp-pda-ui-ringtone-button");
            AccessRingtoneButton.Description = Loc.GetString("comp-pda-ui-ringtone-button-description");
            ActivateMusicButton.Text = Loc.GetString("pda-bound-user-interface-music-button");
            ActivateMusicButton.Description = Loc.GetString("pda-bound-user-interface-music-button-description");
            ShowUplinkButton.Text = Loc.GetString("pda-bound-user-interface-show-uplink-title");
            ShowUplinkButton.Description = Loc.GetString("pda-bound-user-interface-show-uplink-description");
            LockUplinkButton.Text = Loc.GetString("pda-bound-user-interface-lock-uplink-title");
            LockUplinkButton.Description = Loc.GetString("pda-bound-user-interface-lock-uplink-description");

            ViewContainer.OnChildAdded += control => control.Visible = false;

            HomeButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/home.png"));
            FlashLightToggleButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/light.png"));
            EjectPenButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/pencil.png"));
            EjectIdButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/eject.png"));
            EjectPaiButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/pai.png"));
            ProgramCloseButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/Nano/cross.svg.png"));


            HomeButton.OnPressed += _ => ToHomeScreen();

            ProgramListButton.OnPressed += _ =>
            {
                HomeButton.IsCurrent = false;
                ProgramListButton.IsCurrent = true;
                ServicesButton.IsCurrent = false;
                SettingsButton.IsCurrent = false;
                ProgramTitle.IsCurrent = false;

                ChangeView(ProgramListView);
            };

            ServicesButton.OnPressed += _ =>
            {
                HomeButton.IsCurrent = false;
                ProgramListButton.IsCurrent = false;
                ServicesButton.IsCurrent = true;
                SettingsButton.IsCurrent = false;
                ProgramTitle.IsCurrent = false;

                ChangeView(ServicesView);
            };


            SettingsButton.OnPressed += _ =>
            {
                HomeButton.IsCurrent = false;
                ProgramListButton.IsCurrent = false;
                ServicesButton.IsCurrent = false;
                SettingsButton.IsCurrent = true;
                ProgramTitle.IsCurrent = false;

                ChangeView(SettingsView);
            };

            ProgramTitle.OnPressed += _ =>
            {
                HomeButton.IsCurrent = false;
                ProgramListButton.IsCurrent = false;
                ServicesButton.IsCurrent = false;
                SettingsButton.IsCurrent = false;
                ProgramTitle.IsCurrent = true;

                ChangeView(ProgramContentView);
            };

            ProgramCloseButton.OnPressed += _ =>
            {
                HideProgramHeader();
                ToHomeScreen();
            };

            PdaOwnerButton.OnPressed += _ =>
            {
                CopyToClipboard(_pdaOwner, "comp-pda-ui-copy-owner");
            };

            IdInfoButton.OnPressed += _ =>
            {
                CopyToClipboard(_owner + ", " + _jobTitle, "comp-pda-ui-copy-id");
            };

            StationNameButton.OnPressed += _ =>
            {
                CopyToClipboard(_stationName, "comp-pda-ui-copy-sector");
            };

            StationAlertLevelButton.OnPressed += _ =>
            {
                CopyToClipboard(_alertLevel, "comp-pda-ui-copy-alert");
            };

            // Frontier
            BalanceButton.OnPressed += _ =>
            {
                CopyToClipboard(_balance, "comp-pda-ui-copy-balance");
            };
            BankIdButton.OnPressed += _ =>
            {
                CopyToClipboard(_bankAccountId, "comp-pda-ui-copy-bank-id");
            };
            BankTransferButton.OnPressed += _ => SubmitBankTransfer();
            BankTransferConfirmButton.OnPressed += _ =>
            {
                if (_bankTransferConfirmation != null)
                    OnBankTransferPressed?.Invoke(_bankTransferConfirmation.OperationId);
            };
            BankTransferCancelButton.OnPressed += _ =>
            {
                if (_bankTransferConfirmation != null)
                    OnBankTransferCancelPressed?.Invoke(_bankTransferConfirmation.OperationId);
            };
            BankTransferAcknowledgeButton.OnPressed += _ =>
            {
                if (_bankTransferRecovery != null)
                    OnBankTransferAcknowledgePressed?.Invoke(_bankTransferRecovery.OperationId);
            };
            DonationShopInfoButton.OnPressed += _ =>
            {
                CopyToClipboard(_donationShopInfo, "comp-pda-ui-copy-support");
            };
            ShuttleDeedButton.OnPressed += _ =>
            {
                CopyToClipboard(_shuttleDeed, "comp-pda-ui-copy-vessel");
            };
            // End Frontier

            StationTimeButton.OnPressed += _ =>
            {
                var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);
                CopyToClipboard(FormatStationTime(stationTime), "comp-pda-ui-copy-time");
            };

            StationAlertLevelInstructionsButton.OnPressed += _ =>
            {
                CopyToClipboard(_instructions, "comp-pda-ui-copy-advisory");
            };




            HideAllViews();
            ToHomeScreen();
        }

        public void UpdateState(PdaUpdateState state)
        {
            FlashLightToggleButton.IsActive = state.FlashlightEnabled;
            GoldFrameVisible = state.HasGoldPdaFrame;

            if (state.PdaOwnerInfo.ActualOwnerName != null)
            {
                _pdaOwner = state.PdaOwnerInfo.ActualOwnerName;

                // Check if we have company information to display
                if (!string.IsNullOrWhiteSpace(state.PdaOwnerInfo.CompanyName))
                {
                    PdaOwnerLabel.SetMarkup(Loc.GetString("comp-pda-ui-owner-with-company",
                        ("actualOwnerName", _pdaOwner),
                        ("companyName", state.PdaOwnerInfo.CompanyName),
                        ("companyColor", state.PdaOwnerInfo.CompanyColor.ToHex())));
                }
                else
                {
                    PdaOwnerLabel.SetMarkup(Loc.GetString("comp-pda-ui-owner",
                        ("actualOwnerName", _pdaOwner)));
                }
                PdaOwnerLabel.Visible = true;
                PdaOwnerButton.Visible = true;
            }
            else
            {
                PdaOwnerLabel.Visible = false;
                PdaOwnerButton.Visible = false;
            }


            if (state.PdaOwnerInfo.IdOwner != null || state.PdaOwnerInfo.JobTitle != null)
            {
                _owner = state.PdaOwnerInfo.IdOwner ?? Loc.GetString("comp-pda-ui-unknown");
                _jobTitle = state.PdaOwnerInfo.JobTitle ?? Loc.GetString("comp-pda-ui-unassigned");
                IdInfoLabel.SetMarkup(Loc.GetString("comp-pda-ui",
                    ("owner", _owner),
                    ("jobTitle", _jobTitle)));
            }
            else
            {
                IdInfoLabel.SetMarkup(Loc.GetString("comp-pda-ui-blank"));
            }

            _stationName = state.StationName ?? Loc.GetString("comp-pda-ui-unknown");
            StationNameLabel.SetMarkup(Loc.GetString("comp-pda-ui-station",
                ("station", _stationName)));

            _balance = BankSystemExtensions.ToSpesoString(state.Balance); // Frontier
            if (state.PayrollHourly > 0)
            {
                BalanceLabel.SetMarkup(Loc.GetString("comp-pda-ui-balance-payroll",
                    ("balance", _balance),
                    ("hourly", BankSystemExtensions.ToSpesoString(state.PayrollHourly)),
                    ("minutes", FormatPayrollMinutes(state.PayrollNextSeconds))));
            }
            else
            {
                BalanceLabel.SetMarkup(Loc.GetString("comp-pda-ui-balance", ("balance", _balance))); // Frontier
            }
            _bankAccountId = state.BankAccountId ?? Loc.GetString("comp-pda-ui-unknown"); // Frontier
            BankIdLabel.SetMarkup(Loc.GetString("comp-pda-ui-bank-id", ("id", _bankAccountId))); // Frontier
            BankTransferStatusLabel.SetMarkup(state.BankTransferStatus ?? string.Empty); // Frontier
            UpdateBankTransferState(state); // LuaM
            UpdateDonationShop(state); // LuaM

            _shuttleDeed = state.OwnedShipName ?? ""; // Frontier
            ShuttleDeedLabel.SetMarkup(Loc.GetString("comp-pda-ui-shuttle-deed", ("shipname", _shuttleDeed))); // Frontier
            ShuttleDeedSection.Visible = !string.IsNullOrEmpty(state.OwnedShipName); // Frontier

            UpdateStationTime(force: true);

            var alertLevel = state.PdaOwnerInfo.StationAlertLevel;
            var alertColor = state.PdaOwnerInfo.StationAlertColor;
            var alertLevelKey = alertLevel != null ? $"alert-level-{alertLevel}" : "alert-level-unknown";
            _alertLevel = Loc.GetString(alertLevelKey);

            StationAlertLevelLabel.SetMarkup(Loc.GetString(
                "comp-pda-ui-station-alert-level",
                ("color", alertColor),
                ("level", _alertLevel)
            ));
            _instructions = Loc.GetString($"{alertLevelKey}-instructions");
            StationAlertLevelInstructions.SetMarkup(Loc.GetString(
                "comp-pda-ui-station-alert-level-instructions",
                ("instructions", _instructions))
            );

            AddressLabel.Text = state.Address?.ToUpper() ?? " - ";

            EjectIdButton.IsActive = state.PdaOwnerInfo.IdOwner != null || state.PdaOwnerInfo.JobTitle != null;
            EjectPenButton.IsActive = state.HasPen;
            EjectPaiButton.IsActive = state.HasPai;
            EjectIdButton.Disabled = !EjectIdButton.IsActive;
            EjectPenButton.Disabled = !state.HasPen;
            EjectPaiButton.Disabled = !state.HasPai;
            ActivateMusicButton.Visible = state.CanPlayMusic;
            ShowUplinkButton.Visible = state.HasUplink;
            LockUplinkButton.Visible = state.HasUplink;
        }

        private void SubmitBankTransfer()
        {
            var recipientId = BankTransferRecipientEdit.Text.Trim();
            if (string.IsNullOrWhiteSpace(recipientId))
            {
                BankTransferStatusLabel.SetMarkup(Loc.GetString("comp-pda-ui-bank-transfer-missing-recipient"));
                return;
            }

            if (!TryParseBankTransferAmount(BankTransferAmountEdit.Text, out var amount))
            {
                BankTransferStatusLabel.SetMarkup(Loc.GetString("comp-pda-ui-bank-transfer-invalid-amount"));
                return;
            }

            BankTransferButton.Disabled = true;
            OnBankTransferPreviewPressed?.Invoke(recipientId, amount);
        }

        private void CopyToClipboard(string value, string labelLocId)
        {
            _clipboard.SetText(value);
            ClipboardStatusLabel.Text = Loc.GetString(
                "comp-pda-ui-copied",
                ("label", Loc.GetString(labelLocId)));
        }

        private void UpdateBankTransferState(PdaUpdateState state)
        {
            _bankTransferConfirmation = state.BankTransferConfirmation;
            _bankTransferRecovery = state.BankTransferRecovery;

            BankTransferConfirmationPanel.Visible = _bankTransferConfirmation != null;
            BankTransferRecoveryPanel.Visible = _bankTransferRecovery != null;

            if (_bankTransferConfirmation != null)
            {
                BankTransferConfirmationLabel.SetMarkup(Loc.GetString(
                    "comp-pda-ui-bank-transfer-confirmation",
                    ("recipient", _bankTransferConfirmation.RecipientName),
                    ("id", _bankTransferConfirmation.RecipientBankId),
                    ("amount", BankSystemExtensions.ToSpesoString(_bankTransferConfirmation.Amount)),
                    ("operation", _bankTransferConfirmation.OperationId.ToString("N"))));
            }

            if (_bankTransferRecovery != null)
            {
                BankTransferRecoveryLabel.SetMarkup(Loc.GetString(
                    "comp-pda-ui-bank-transfer-recovered",
                    ("recipient", _bankTransferRecovery.RecipientName),
                    ("id", _bankTransferRecovery.RecipientBankId),
                    ("amount", BankSystemExtensions.ToSpesoString(_bankTransferRecovery.Amount)),
                    ("balance", BankSystemExtensions.ToSpesoString(_bankTransferRecovery.SenderBalance)),
                    ("operation", _bankTransferRecovery.OperationId.ToString("N"))));
            }

            var locked = !state.BankTransferReady ||
                         state.BankTransferRetryBlocked ||
                         _bankTransferConfirmation != null ||
                         _bankTransferRecovery != null;
            BankTransferButton.Disabled = locked;
            BankTransferRecipientEdit.Editable = !locked;
            BankTransferAmountEdit.Editable = !locked;
            BankTransferConfirmButton.Disabled = _bankTransferConfirmation == null || state.BankTransferRetryBlocked;
            BankTransferCancelButton.Disabled = _bankTransferConfirmation == null;
            BankTransferAcknowledgeButton.Disabled = _bankTransferRecovery == null;
        }

        private static bool TryParseBankTransferAmount(string value, out int amount)
        {
            var normalized = string.Concat(value.Where(ch => !char.IsWhiteSpace(ch)));
            return int.TryParse(
                       normalized,
                       NumberStyles.None,
                       CultureInfo.InvariantCulture,
                       out amount) &&
                   amount > 0;
        }

        private static int FormatPayrollMinutes(int nextSeconds)
        {
            if (nextSeconds <= 0)
                return 0;

            return Math.Max(1, (int) Math.Ceiling(nextSeconds / 60f));
        }

        private void UpdateDonationShop(PdaUpdateState state)
        {
            var accessUntil = string.IsNullOrWhiteSpace(state.DonationShopAccessUntil)
                ? Loc.GetString("comp-pda-ui-donation-shop-no-access-until")
                : state.DonationShopAccessUntil;

            _donationShopInfo = Loc.GetString("comp-pda-ui-donation-shop-copy",
                ("balance", state.DonationBalance),
                ("currency", DonationCurrencyCode),
                ("until", accessUntil));

            DonationShopInfoLabel.SetMarkup(Loc.GetString(
                state.DonationShopAccess
                    ? "comp-pda-ui-donation-shop-access"
                    : "comp-pda-ui-donation-shop-locked",
                ("balance", state.DonationBalance),
                ("currency", DonationCurrencyCode),
                ("until", accessUntil)));

            DonationShopStatusLabel.SetMarkup(state.DonationShopStatus ?? string.Empty);
            DonationShopListings.RemoveAllChildren();

            foreach (var listing in state.DonationShopListings)
            {
                var name = Loc.GetString(listing.NameLocId);
                var description = Loc.GetString(listing.DescriptionLocId);
                var buttonText = GetDonationShopButtonText(state, listing);
                var disabled = !listing.Available;

                var card = new PanelContainer
                {
                    StyleClasses = { "PdaListingCard" },
                    HorizontalExpand = true,
                    Margin = new Thickness(3),
                };

                var box = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    HorizontalExpand = true,
                    Margin = new Thickness(9, 7),
                };

                box.AddChild(new Label
                {
                    Text = name,
                    StyleClasses = { "PdaListingTitle" },
                });

                var descriptionLabel = new RichTextLabel();
                descriptionLabel.SetMarkup(description);
                box.AddChild(descriptionLabel);

                var priceLabel = new RichTextLabel
                {
                    Margin = new Thickness(0, 5, 0, 5),
                };
                priceLabel.SetMarkup(Loc.GetString("comp-pda-ui-donation-shop-price",
                    ("price", listing.Price),
                    ("currency", DonationCurrencyCode)));
                box.AddChild(priceLabel);

                var button = new Button
                {
                    Text = buttonText,
                    Disabled = disabled,
                    HorizontalExpand = true,
                };
                button.OnPressed += _ => OnDonationShopPurchasePressed?.Invoke(listing.Id);

                box.AddChild(button);
                card.AddChild(box);
                DonationShopListings.AddChild(card);
            }
        }

        private static string GetDonationShopButtonText(PdaUpdateState state, PdaDonationShopListing listing)
        {
            if (listing.Owned)
                return Loc.GetString("comp-pda-ui-donation-shop-owned");

            if (!state.DonationShopAccess)
                return Loc.GetString("comp-pda-ui-donation-shop-locked-button");

            if (state.DonationBalance < listing.Price)
            {
                return Loc.GetString("comp-pda-ui-donation-shop-insufficient",
                    ("price", listing.Price),
                    ("currency", DonationCurrencyCode));
            }

            if (!listing.Available)
                return Loc.GetString("comp-pda-ui-donation-shop-unavailable");

            return Loc.GetString("comp-pda-ui-donation-shop-buy");
        }

        public void UpdateAvailablePrograms(List<(EntityUid, CartridgeComponent)> programs)
        {
            ProgramList.RemoveAllChildren();

            if (programs.Count == 0)
            {
                ProgramList.AddChild(new Label()
                {
                    Text = Loc.GetString("comp-pda-io-no-programs-available"),
                    HorizontalAlignment = HAlignment.Center,
                    VerticalAlignment = VAlignment.Center,
                    VerticalExpand = true
                });

                return;
            }

            foreach (var (uid, component) in programs)
            {
                var item = new PdaProgramItem();

                if (component.Icon is not null)
                    item.Icon.SetFromSpriteSpecifier(component.Icon);

                item.OnPressed += _ => OnProgramItemPressed?.Invoke(uid);

                switch (component.InstallationStatus)
                {
                    case InstallationStatus.Cartridge:
                        item.InstallButton.Visible = true;
                        item.InstallButton.Text = Loc.GetString("cartridge-bound-user-interface-install-button");
                        item.InstallButton.OnPressed += _ => OnInstallButtonPressed?.Invoke(uid);
                        break;
                    case InstallationStatus.Installed:
                        item.InstallButton.Visible = true;
                        item.InstallButton.Text = Loc.GetString("cartridge-bound-user-interface-uninstall-button");
                        item.InstallButton.OnPressed += _ => OnUninstallButtonPressed?.Invoke(uid);
                        break;
                }

                item.ProgramName.Text = Loc.GetString(component.ProgramName);
                ProgramList.AddChild(item);
            }
        }

        /// <summary>
        /// Changes the current view to the home screen (view 0) and sets the tabs `IsCurrent` flag accordingly
        /// </summary>
        public void ToHomeScreen()
        {
            HomeButton.IsCurrent = true;
            ProgramListButton.IsCurrent = false;
            ServicesButton.IsCurrent = false;
            SettingsButton.IsCurrent = false;
            ProgramTitle.IsCurrent = false;

            ChangeView(HomeView);
        }

        /// <summary>
        /// Hides the program title and close button.
        /// </summary>
        public void HideProgramHeader()
        {
            ProgramTitle.IsCurrent = false;
            ProgramTitle.Visible = false;
            ProgramCloseButton.Visible = false;
            ProgramListButton.Visible = true;
            ServicesButton.Visible = true;
            SettingsButton.Visible = true;
            NavigationSpacer.Visible = true;
        }

        /// <summary>
        /// Changes the current view to the program content view (view 3), sets the program title and sets the tabs `IsCurrent` flag accordingly
        /// </summary>
        public void ToProgramView(string title)
        {
            HomeButton.IsCurrent = false;
            ProgramListButton.IsCurrent = false;
            ServicesButton.IsCurrent = false;
            SettingsButton.IsCurrent = false;
            ProgramTitle.IsCurrent = false;
            ProgramTitle.IsCurrent = true;
            ProgramTitle.Visible = true;
            ProgramCloseButton.Visible = true;
            ProgramListButton.Visible = false;
            ServicesButton.Visible = false;
            SettingsButton.Visible = false;
            NavigationSpacer.Visible = false;

            ProgramTitle.LabelText = title;
            ProgramTitle.ToolTip = title;
            ChangeView(ProgramContentView);
        }


        /// <summary>
        /// Changes the current view to the given view number
        /// </summary>
        public void ChangeView(int view)
        {
            if (ViewContainer.ChildCount <= view)
                return;

            ViewContainer.GetChild(_currentView).Visible = false;
            ViewContainer.GetChild(view).Visible = true;
            _currentView = view;
        }

        private void HideAllViews()
        {
            var views = ViewContainer.Children;
            foreach (var view in views)
            {
                view.Visible = false;
            }
        }

        protected override void Draw(DrawingHandleScreen handle)
        {
            base.Draw(handle);

            UpdateStationTime();
        }

        private void UpdateStationTime(bool force = false)
        {
            var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);
            var elapsedSecond = Math.Max(0L, (long) stationTime.TotalSeconds);
            if (!force && elapsedSecond == _lastDisplayedStationSecond)
                return;

            _lastDisplayedStationSecond = elapsedSecond;
            StationTimeLabel.SetMarkup(Loc.GetString("comp-pda-ui-station-time",
                ("time", FormatStationTime(stationTime))));
        }

        private static string FormatStationTime(TimeSpan stationTime)
        {
            if (stationTime < TimeSpan.Zero)
                stationTime = TimeSpan.Zero;

            return $"{(int) stationTime.TotalHours:00}:{stationTime.Minutes:00}:{stationTime.Seconds:00}";
        }
    }
}
