using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.PDA;

[GenerateTypedNameReferences]
public sealed partial class PdaNavigationButton : ContainerButton
{
    private bool _xamlLoaded;
    private bool _isCurrent;
    private bool _isActive = true;

    private Thickness _borderThickness = new(0, 0, 0, 2);
    private Thickness _currentTabBorderThickness = new(2, 0, 2, 0);

    private readonly StyleBoxFlat _styleBox = new()
    {
        BackgroundColor = Color.FromHex("#12191C"),
        BorderColor = Color.FromHex("#33464E"),
        BorderThickness = new Thickness(0, 0, 0, 2)
    };

    public string InactiveBgColor { get; set; } = "#12191C";
    public string ActiveBgColor { get; set; } = "#1D343B";
    public string HoverBgColor { get; set; } = "#1A292E";
    public string PressedBgColor { get; set; } = "#0E1416";
    public string InactiveFgColor { get; set; } = "#66777D";
    public string ActiveFgColor { get; set; } = "#DCE8EB";

    public SpriteSpecifier? IconTexture
    {
        set
        {
            Icon.Visible = value != null;
            Label.Visible = value == null;

            if (value is not null)
                Icon.SetFromSpriteSpecifier(value);
        }
    }

    public Vector2 IconScale
    {
        get => Icon.DisplayRect.TextureScale;
        set => Icon.DisplayRect.TextureScale = value;
    }

    public string? LabelText
    {
        get => Label.Text;
        set => Label.Text = value;
    }

    /// <summary>
    /// Sets the border thickness when the tab is not the currently active one
    /// </summary>
    public Thickness BorderThickness
    {
        get => _borderThickness;
        set
        {
            _borderThickness = value;
            UpdateVisualState();
        }
    }

    /// <summary>
    /// Sets the border thickness when this tab is the currently active tab
    /// </summary>
    public Thickness CurrentTabBorderThickness
    {
        get => _currentTabBorderThickness;
        set
        {
            _currentTabBorderThickness = value;
            UpdateVisualState();
        }
    }

    public bool IsCurrent
    {
        get => _isCurrent;
        set
        {
            _isCurrent = value;
            UpdateVisualState();
        }
    }

    public bool IsActive
    {
        get => _isActive;
        set
        {
            _isActive = value;
            UpdateVisualState();
        }
    }

    public PdaNavigationButton()
    {
        RobustXamlLoader.Load(this);
        Background.PanelOverride = _styleBox;
        _xamlLoaded = true;
        UpdateVisualState();
    }

    protected override void DrawModeChanged()
    {
        base.DrawModeChanged();
        UpdateVisualState();
    }

    private void UpdateVisualState()
    {
        // ContainerButton invokes DrawModeChanged from its base constructor,
        // before this control's XAML namespace and named children exist.
        if (!_xamlLoaded)
            return;

        var background = _isCurrent
            ? ActiveBgColor
            : DrawMode switch
            {
                DrawModeEnum.Hover => HoverBgColor,
                DrawModeEnum.Pressed => PressedBgColor,
                _ => InactiveBgColor,
            };

        _styleBox.BackgroundColor = Color.FromHex(background);
        _styleBox.BorderThickness = _isCurrent ? _currentTabBorderThickness : _borderThickness;

        var foreground = Color.FromHex(_isActive ? ActiveFgColor : InactiveFgColor);
        Icon.Modulate = foreground;
        Label.FontColorOverride = foreground;
    }
}
