using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._NF.LateJoin.ListItems;

[GenerateTypedNameReferences]
public sealed partial class JobListItem : Button
{
    public sealed class ViewState(string jobId, string jobName, string toolTip, bool disabled, Texture? jobIcon, Color? displayColor)
    {
        public string JobId { get; } = jobId;
        public string JobName { get; } = jobName;

        public bool Disabled { get; } = disabled;

        public string ToolTip { get; } = toolTip;

        public Texture? JobIcon { get; } = jobIcon;
        public Color? DisplayColor { get; } = displayColor;
    }

    public JobListItem(ViewState state)
    {
        RobustXamlLoader.Load(this);
        JobText.Text = state.JobName;
        JobText.FontColorOverride = state.DisplayColor;
        JobIcon.Texture = state.JobIcon;
        if (!string.IsNullOrWhiteSpace(state.ToolTip))
        {
            TooltipSupplier = _ =>
            {
                var message = new FormattedMessage();
                message.AddMarkupPermissive(state.ToolTip);
                var tooltip = new Tooltip();
                tooltip.SetMessage(message);
                return tooltip;
            };
        }
        Disabled = state.Disabled;
    }
}
