using Content.Client._NF.Bank;
using Content.Client.UserInterface.Controls;
using Content.Shared._NF.Bank;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using System.Globalization;
using System.Linq;

namespace Content.Client._NF.Bank.UI;

[GenerateTypedNameReferences]
public sealed partial class BankATMMenu : FancyWindow
{
    [Dependency] private IEntityManager _ent = default!;
    private readonly BankSystem _bank;

    public Action? WithdrawRequest;
    public Action? DepositRequest;
    public int Amount;
    public int BankAmount;
    public BankATMMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _bank = _ent.System<BankSystem>();

        WithdrawButton.OnPressed += OnWithdrawPressed;
        DepositButton.OnPressed += OnDepositPressed;
        Title = Loc.GetString("bank-atm-menu-title");
        WithdrawEdit.OnTextChanged += OnAmountChanged;
    }

    public void SetBalance(int amount, long savings)
    {
        BalanceLabel.Text = BankSystemExtensions.ToSpesoString(amount);
        SavingsLabel.Text = BankSystemExtensions.ToSpesoString(savings);
        BankAmount = amount;
    }

    public void SetDeposit(int amount)
    {
        DepositButton.Disabled = amount <= 0;
        if (amount >= 0) // Valid
        {
            _bank.GetTaxedDepositAmount(amount, BankAmount, out var afterTax, out var taxedAway);
            DepositLabel.Text = BankSystemExtensions.ToSpesoString(afterTax);
            DepositLabelUT.Text = BankSystemExtensions.ToSpesoString(taxedAway);
        }
        else
        {
            DepositLabel.Text = Loc.GetString("bank-atm-menu-cash-error");
            DepositLabelUT.Text = Loc.GetString("bank-atm-menu-cash-error");
        }
    }

    public void SetEnabled(bool enabled)
    {
        WithdrawButton.Disabled = !enabled;
    }

    private void OnWithdrawPressed(BaseButton.ButtonEventArgs obj)
    {
        WithdrawRequest?.Invoke();
    }

    private void OnDepositPressed(BaseButton.ButtonEventArgs obj)
    {
        DepositRequest?.Invoke();
    }

    private void OnAmountChanged(LineEdit.LineEditEventArgs args)
    {
        // The same field is used for deposits and withdrawals. Accept ordinary
        // grouping such as "10 000" instead of silently keeping a stale amount
        // when the player adds a space.
        var normalized = string.Concat(args.Text.Where(ch => !char.IsWhiteSpace(ch)));
        Amount = int.TryParse(
                     normalized,
                     NumberStyles.None,
                     CultureInfo.InvariantCulture,
                     out var amount) &&
                 amount > 0
            ? amount
            : 0;
    }
}
