using Content.Shared.Mech;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Mech.Ui.Equipment;

[GenerateTypedNameReferences]
public sealed partial class MechGrabberUiFragment : BoxContainer
{
    [Dependency] private IEntityManager _entity = default!;

    public event Action<EntityUid>? OnEjectAction;

    public MechGrabberUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateContents(MechGrabberUiState state)
    {
        ItemList.Clear();
        SpaceLabel.Text = $"{state.Contents.Count}/{state.MaxContents}";
        foreach (var netEntity in state.Contents)
        {
            if (!_entity.TryGetEntity(netEntity, out var ent) ||
                ent == null ||
                !_entity.TryGetComponent<MetaDataComponent>(ent.Value, out var meta))
                continue;

            var entity = ent.Value;
            var item = ItemList.AddItem(meta.EntityName);
            item.OnSelected += _ => OnEjectAction?.Invoke(entity);
        }
    }
}
