using Content.Shared.Radio;
using Robust.Client.UserInterface.Controls;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Radio;

[GenerateTypedNameReferences]
public sealed partial class TelecomKeyServiceWindow : FancyWindow
{
    public event Action<TelecomCreateKeyMessage>? CreateKey;
    public event Action<bool>? ToggleLock;
    private readonly LineEdit _frequency;
    private readonly LineEdit _channelName;
    private readonly LineEdit _tag;
    private readonly LineEdit _color;
    private readonly Button _lock;
    private readonly RichTextLabel _status;

    public TelecomKeyServiceWindow()
    {
        RobustXamlLoader.Load(this);
        _frequency = FindControl<LineEdit>("Frequency");
        _channelName = FindControl<LineEdit>("ChannelName");
        _tag = FindControl<LineEdit>("Tag");
        _color = FindControl<LineEdit>("Color");
        _lock = FindControl<Button>("Lock");
        _status = FindControl<RichTextLabel>("Status");
        FindControl<Button>("Create").OnPressed += _ => CreateKeyClicked();
        _lock.OnPressed += _ => ToggleLock?.Invoke(_lock.Text == Loc.GetString("telecom-key-console-unlock"));
    }

    private void CreateKeyClicked()
    {
        if (!int.TryParse(_frequency.Text, out var frequency))
            return;
        CreateKey?.Invoke(new TelecomCreateKeyMessage
        {
            Frequency = frequency, ChannelName = _channelName.Text, Tag = _tag.Text, Color = _color.Text
        });
    }

    public void UpdateState(TelecomKeyServiceState state)
    {
        _lock.Text = Loc.GetString(state.KeysLocked ? "telecom-key-console-unlock" : "telecom-key-console-lock");
        if (state.Error != null)
            _status.SetMessage(Loc.GetString(state.Error));
    }

}
