using System.Linq;
using Content.Client.Decals.UI;
using Content.Shared.Radio;
using Robust.Client.UserInterface.Controls;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Radio;

[GenerateTypedNameReferences]
public sealed partial class TelecomKeyServiceWindow : FancyWindow
{
    public event Action<TelecomCreateKeyMessage>? CreateKey;
    public event Action<bool>? ToggleLock;
    private readonly LineEdit _frequency;
    private readonly LineEdit _channelName;
    private readonly LineEdit _tag;
    private readonly ColorSelectorSliders _colorPickerStart;
    private readonly ColorSelectorSliders _colorPickerEnd;
    private readonly CheckBox _useGradient;
    private readonly Button _lock;
    private readonly RichTextLabel _status;
    private PaletteColorPicker? _startPalette;
    private PaletteColorPicker? _endPalette;

    public TelecomKeyServiceWindow()
    {
        RobustXamlLoader.Load(this);
        _frequency = FindControl<LineEdit>("Frequency");
        _channelName = FindControl<LineEdit>("ChannelName");
        _tag = FindControl<LineEdit>("Tag");
        _colorPickerStart = FindControl<ColorSelectorSliders>("ColorPickerStart");
        _colorPickerEnd = FindControl<ColorSelectorSliders>("ColorPickerEnd");
        _useGradient = FindControl<CheckBox>("UseGradient");
        _lock = FindControl<Button>("Lock");
        _status = FindControl<RichTextLabel>("Status");

        _colorPickerStart.Color = Color.Green;
        _colorPickerEnd.Color = Color.Lime;

        FindControl<Button>("PaletteStart").OnPressed += _ => TogglePalette(ref _startPalette, color => _colorPickerStart.Color = color);
        FindControl<Button>("PaletteEnd").OnPressed += _ => TogglePalette(ref _endPalette, color => _colorPickerEnd.Color = color);
        FindControl<Button>("Create").OnPressed += _ => CreateKeyClicked();
        _lock.OnPressed += _ => ToggleLock?.Invoke(_lock.Text == Loc.GetString("telecom-key-console-unlock"));
    }

    private void CreateKeyClicked()
    {
        if (!int.TryParse(_frequency.Text, out var frequency))
            return;
        CreateKey?.Invoke(new TelecomCreateKeyMessage
        {
            Frequency = frequency,
            ChannelName = _channelName.Text,
            Tag = _tag.Text,
            Color = _colorPickerStart.Color.ToHex(),
            GradientColor = _useGradient.Pressed ? _colorPickerEnd.Color.ToHex() : null
        });
    }

    private void TogglePalette(ref PaletteColorPicker? picker, Action<Color> setColor)
    {
        if (picker == null)
        {
            picker = new PaletteColorPicker();
            picker.PaletteList.OnItemSelected += args =>
            {
                var selected = args.ItemList.GetSelected().FirstOrDefault();
                if (selected?.Metadata is Color color)
                    setColor(color);
            };
            picker.OpenToLeft();
            return;
        }

        if (picker.IsOpen)
            picker.Close();
        else
            picker.Open();
    }

    public void UpdateState(TelecomKeyServiceState state)
    {
        _lock.Text = Loc.GetString(state.KeysLocked ? "telecom-key-console-unlock" : "telecom-key-console-lock");
        if (state.Error != null)
            _status.SetMessage(Loc.GetString(state.Error));
    }

}
