using System.Linq;
using Content.Client.Decals.UI;
using Content.Shared.Radio;
using Robust.Client.UserInterface.Controls;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;

namespace Content.Client.Radio;

[GenerateTypedNameReferences]
public sealed partial class TelecomKeyServiceWindow : FancyWindow
{
    public event Action<TelecomCreateKeyMessage>? CreateKey;
    public event Action<bool>? ToggleLock;
    public event Action<NetEntity>? DeleteKey;
    public event Action? DeleteAllKeys;
    public event Action<int>? DetachFrequency;
    private readonly LineEdit _frequency;
    private readonly LineEdit _password;
    private readonly LineEdit _channelName;
    private readonly LineEdit _tag;
    private readonly ColorSelectorSliders _colorPickerStart;
    private readonly ColorSelectorSliders _colorPickerEnd;
    private readonly CheckBox _useGradient;
    private readonly Button _lock;
    private readonly RichTextLabel _status;
    private readonly BoxContainer _keyList;
    private readonly TabContainer _tabs;
    private PaletteColorPicker? _startPalette;
    private PaletteColorPicker? _endPalette;

    public TelecomKeyServiceWindow()
    {
        RobustXamlLoader.Load(this);
        _frequency = FindControl<LineEdit>("Frequency");
        _password = FindControl<LineEdit>("Password");
        _channelName = FindControl<LineEdit>("ChannelName");
        _tag = FindControl<LineEdit>("Tag");
        _colorPickerStart = FindControl<ColorSelectorSliders>("ColorPickerStart");
        _colorPickerEnd = FindControl<ColorSelectorSliders>("ColorPickerEnd");
        _useGradient = FindControl<CheckBox>("UseGradient");
        _lock = FindControl<Button>("Lock");
        _status = FindControl<RichTextLabel>("Status");
        _keyList = FindControl<BoxContainer>("KeyList");
        _tabs = FindControl<TabContainer>("Tabs");
        _tabs.SetTabTitle(0, Loc.GetString("telecom-key-console-create-tab"));
        _tabs.SetTabTitle(1, Loc.GetString("telecom-key-console-management-tab"));

        _colorPickerStart.Color = Color.Green;
        _colorPickerEnd.Color = Color.Lime;

        FindControl<Button>("PaletteStart").OnPressed += _ => TogglePalette(ref _startPalette, color => _colorPickerStart.Color = color);
        FindControl<Button>("PaletteEnd").OnPressed += _ => TogglePalette(ref _endPalette, color => _colorPickerEnd.Color = color);
        FindControl<Button>("Create").OnPressed += _ => CreateKeyClicked();
        FindControl<Button>("DeleteAll").OnPressed += _ => DeleteAllKeys?.Invoke();
        _lock.OnPressed += _ => ToggleLock?.Invoke(_lock.Text == Loc.GetString("telecom-key-console-unlock"));
    }

    private void CreateKeyClicked()
    {
        if (!int.TryParse(_frequency.Text, out var frequency))
            return;
        CreateKey?.Invoke(new TelecomCreateKeyMessage
        {
            Frequency = frequency,
            Password = _password.Text,
            ChannelName = _channelName.Text,
            Tag = _tag.Text,
            Color = _colorPickerStart.Color.ToHex(),
            GradientColor = _useGradient.Pressed ? _colorPickerEnd.Color.ToHex() : null
        });
    }

    private void TogglePalette(ref PaletteColorPicker? picker, Action<Color> setColor)
    {
        if (picker == null)
        {
            picker = new PaletteColorPicker();
            picker.PaletteList.OnItemSelected += args =>
            {
                var selected = args.ItemList.GetSelected().FirstOrDefault();
                if (selected?.Metadata is Color color)
                    setColor(color);
            };
            picker.OpenToLeft();
            return;
        }

        if (picker.IsOpen)
            picker.Close();
        else
            picker.Open();
    }

    public void UpdateState(TelecomKeyServiceState state)
    {
        _lock.Text = Loc.GetString(state.KeysLocked ? "telecom-key-console-unlock" : "telecom-key-console-lock");
        if (state.Error != null)
            _status.SetMessage(Loc.GetString(state.Error));
        else
            _status.SetMessage(Loc.GetString("telecom-key-console-key-count", ("count", state.Keys.Count)));

        _keyList.RemoveAllChildren();
        var lastFrequency = (int?) null;
        foreach (var key in state.Keys.OrderBy(key => key.Frequency).ThenBy(key => key.Name))
        {
            var row = new BoxContainer();
            row.AddChild(new Label { Text = $"{key.Frequency} — {key.Name} [{key.Code}]" });

            var clone = new Button { Text = Loc.GetString("telecom-key-console-clone") };
            clone.OnPressed += _ => PrepareClone(key);
            row.AddChild(clone);

            var delete = new Button { Text = Loc.GetString("telecom-key-console-delete") };
            delete.OnPressed += _ => DeleteKey?.Invoke(key.Key);
            row.AddChild(delete);

            if (lastFrequency != key.Frequency)
            {
                var detach = new Button { Text = Loc.GetString("telecom-key-console-detach") };
                detach.OnPressed += _ => DetachFrequency?.Invoke(key.Frequency);
                row.AddChild(detach);
                lastFrequency = key.Frequency;
            }

            _keyList.AddChild(row);
        }
    }

    private void PrepareClone(TelecomOwnedKeyInfo key)
    {
        _tabs.CurrentTab = 0;
        _frequency.Text = key.Frequency.ToString();
        _channelName.Text = key.Name;
        _tag.Text = key.Code;
        if (key.Color != null && Color.TryParse(key.Color, out var color))
            _colorPickerStart.Color = color;
        _useGradient.Pressed = key.GradientColor != null;
        if (key.GradientColor != null && Color.TryParse(key.GradientColor, out var gradient))
            _colorPickerEnd.Color = gradient;
    }

}
