using Content.Shared.Radio;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using System.Linq;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Map;

namespace Content.Client.Radio;

[GenerateTypedNameReferences]
public sealed partial class TelecomLogConsoleWindow : FancyWindow
{
    public event Action<TelecomLogQueryMessage>? Query;
    private readonly OptionButton _map;
    private readonly OptionButton _channel;
    private readonly LineEdit _frequency;
    private readonly LineEdit _speaker;
    private readonly LineEdit _words;
    private readonly LineEdit _from;
    private readonly LineEdit _to;
    private readonly LineEdit _password;
    private readonly RichTextLabel _entries;
    private readonly RichTextLabel _status;

    public TelecomLogConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        _map = FindControl<OptionButton>("Map");
        _channel = FindControl<OptionButton>("Channel");
        _frequency = FindControl<LineEdit>("Frequency");
        _speaker = FindControl<LineEdit>("Speaker");
        _words = FindControl<LineEdit>("Words");
        _from = FindControl<LineEdit>("From");
        _to = FindControl<LineEdit>("To");
        _password = FindControl<LineEdit>("Password");
        _entries = FindControl<RichTextLabel>("Entries");
        _status = FindControl<RichTextLabel>("Status");
        FindControl<Button>("Search").OnPressed += _ => SendQuery();
        _channel.OnItemSelected += args =>
        {
            _selectedChannelId = args.Id;
            _channel.SelectId(args.Id);
        };
    }

    private void SendQuery()
    {
        MapId? map = _map.SelectedId >= 0 && _maps.Count > _map.SelectedId ? _maps[_map.SelectedId] : null;
        var channel = _selectedChannelId > 0 && _channels.Count > _selectedChannelId
            ? _channels[_selectedChannelId - 1].Id
            : null;
        Query?.Invoke(new TelecomLogQueryMessage
        {
            Map = map, Channel = channel, Frequency = _frequency.Text, Speaker = _speaker.Text, Words = _words.Text,
            From = _from.Text, To = _to.Text, Password = _password.Text
        });
    }

    public void UpdateState(TelecomLogConsoleState state)
    {
        _maps = state.Maps;
        _map.Clear();
        foreach (var map in _maps)
            _map.AddItem($"{Loc.GetString("telecom-log-console-map")} {map}");
        _channel.Clear();
        _channel.AddItem(Loc.GetString("telecom-log-console-channel-all"));
        foreach (var channel in state.Channels)
            _channel.AddItem($"{channel.Name} ({channel.Id})");
        if (_channel.ItemCount > 0)
        {
            _channel.SelectId(0);
            _selectedChannelId = 0;
        }
        if (_map.ItemCount > 0 && _map.SelectedId < 0)
            _map.SelectId(0);
        _status.SetMessage(state.Error == null ? Loc.GetString("telecom-log-console-count", ("count", state.Entries.Count)) : Loc.GetString(state.Error));
        _entries.SetMessage(string.Join("\n", state.Entries.Select(entry =>
            $"{entry.Timestamp.ToLocalTime():yyyy-MM-dd HH:mm:ss} [{entry.Map}] [{entry.Channel}/{entry.Frequency}] {entry.Speaker}: {entry.Message}")));
    }

    private List<MapId> _maps = new();
    private List<TelecomChannelInfo> _channels = new();
    private int _selectedChannelId;
}
