#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sqlite3
from pathlib import Path
from typing import Any


ALLOWED_FLAGS = {
    "ADMIN",
    "BAN",
    "DEBUG",
    "FUN",
    "PERMISSIONS",
    "SERVER",
    "SPAWN",
    "VAREDIT",
    "MAPPING",
    "LOGS",
    "ROUND",
    "QUERY",
    "ADMINHELP",
    "VIEWNOTES",
    "EDITNOTES",
    "MASSBAN",
    "STEALTH",
    "ADMINCHAT",
    "PII",
    "MODERATOR",
    "ADMINWHO",
    "NAMECOLOR",
    "WHITELIST",
    "HOST",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate LuaM admin rank SQL from Tools/luam_admin_ranks.yml.")
    parser.add_argument("--input", default="Tools/luam_admin_ranks.yml", help="Rank YAML file.")
    parser.add_argument("--output-dir", default="DeploymentPackages/LuaM", help="Directory for generated SQL files.")
    parser.add_argument("--check-only", action="store_true", help="Validate ranks and rendered SQL without writing files.")
    parser.add_argument("--json", action="store_true", help="Print machine-readable result.")
    return parser.parse_args()


def parse_rank_yaml(path: Path) -> list[dict[str, Any]]:
    ranks: list[dict[str, Any]] = []
    current: dict[str, Any] | None = None
    in_flags = False

    for raw_line in path.read_text(encoding="utf-8-sig").splitlines():
        line = raw_line.rstrip()
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or stripped == "ranks:":
            continue

        if stripped.startswith("- key:"):
            if current is not None:
                ranks.append(current)
            current = {
                "key": parse_scalar(stripped.split(":", 1)[1].strip()),
                "flags": [],
            }
            in_flags = False
            continue

        if current is None:
            raise ValueError(f"Unexpected line outside rank entry: {raw_line}")

        if stripped == "flags:":
            in_flags = True
            continue

        if in_flags and stripped.startswith("- "):
            current["flags"].append(parse_scalar(stripped[2:].strip()))
            continue

        if ":" in stripped:
            key, value = stripped.split(":", 1)
            current[key.strip()] = parse_scalar(value.strip())
            in_flags = False
            continue

        raise ValueError(f"Could not parse line: {raw_line}")

    if current is not None:
        ranks.append(current)

    return sorted(ranks, key=lambda rank: int(rank["order"]))


def parse_scalar(value: str) -> Any:
    value = value.strip()
    if value.startswith('"') and value.endswith('"'):
        return value[1:-1]
    if value.startswith("'") and value.endswith("'"):
        return value[1:-1]
    if value.isdigit():
        return int(value)
    return value


def validate_ranks(ranks: list[dict[str, Any]]) -> None:
    names = set()
    keys = set()
    for rank in ranks:
        for field in ("key", "order", "name", "shortName", "purpose", "flags"):
            if field not in rank:
                raise ValueError(f"Rank entry is missing {field}: {rank}")

        if rank["key"] in keys:
            raise ValueError(f"Duplicate rank key: {rank['key']}")
        keys.add(rank["key"])

        if rank["name"] in names:
            raise ValueError(f"Duplicate rank name: {rank['name']}")
        names.add(rank["name"])

        flags = rank["flags"]
        if not isinstance(flags, list) or not flags:
            raise ValueError(f"Rank {rank['key']} has no flags.")

        duplicate_flags = sorted({flag for flag in flags if flags.count(flag) > 1})
        if duplicate_flags:
            raise ValueError(f"Rank {rank['key']} contains duplicate flag(s): {', '.join(duplicate_flags)}")

        invalid = sorted(set(flags) - ALLOWED_FLAGS)
        if invalid:
            raise ValueError(f"Rank {rank['key']} contains invalid flag(s): {', '.join(invalid)}")

        if "HOST" in flags and rank["key"] != "owner":
            raise ValueError(f"Only owner may contain HOST; found on {rank['key']}")

        if "PERMISSIONS" in flags and rank["key"] not in {"head-admin", "owner"}:
            raise ValueError(f"PERMISSIONS is reserved for head-admin/owner; found on {rank['key']}")


def sql_quote(value: Any) -> str:
    return "'" + str(value).replace("'", "''") + "'"


def render_sqlite(ranks: list[dict[str, Any]]) -> str:
    lines = [
        "-- LuaM admin rank ladder for SQLite.",
        "-- Generated by Tools/generate_luam_admin_rank_sql.py. Review before applying.",
        "BEGIN TRANSACTION;",
        "",
    ]

    for rank in ranks:
        name = sql_quote(rank["name"])
        short = sql_quote(rank["shortName"])
        lines.extend(
            [
                f"-- {rank['order']}. {rank['name']} ({rank['shortName']})",
                f"INSERT INTO admin_rank (name, short_name)",
                f"SELECT {name}, {short}",
                f"WHERE NOT EXISTS (SELECT 1 FROM admin_rank WHERE name = {name});",
                f"UPDATE admin_rank SET short_name = {short} WHERE name = {name};",
                f"DELETE FROM admin_rank_flag",
                f"WHERE admin_rank_id IN (SELECT admin_rank_id FROM admin_rank WHERE name = {name});",
            ]
        )

        for flag in rank["flags"]:
            lines.append(
                "INSERT INTO admin_rank_flag (flag, admin_rank_id) "
                f"SELECT {sql_quote(flag)}, admin_rank_id FROM admin_rank WHERE name = {name};"
            )
        lines.append("")

    lines.append("COMMIT;")
    lines.append("")
    return "\n".join(lines)


def validate_sqlite_import(ranks: list[dict[str, Any]]) -> dict[str, int]:
    connection = sqlite3.connect(":memory:")
    try:
        connection.executescript(
            """
            CREATE TABLE admin_rank (
                admin_rank_id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                short_name TEXT NOT NULL DEFAULT ''
            );
            CREATE TABLE admin_rank_flag (
                admin_rank_flag_id INTEGER PRIMARY KEY AUTOINCREMENT,
                flag TEXT NOT NULL,
                admin_rank_id INTEGER NOT NULL,
                FOREIGN KEY(admin_rank_id) REFERENCES admin_rank(admin_rank_id) ON DELETE CASCADE
            );
            """
        )
        connection.executescript(render_sqlite(ranks))

        rank_count = connection.execute("SELECT COUNT(*) FROM admin_rank").fetchone()[0]
        flag_count = connection.execute("SELECT COUNT(*) FROM admin_rank_flag").fetchone()[0]
        expected_flags = sum(len(rank["flags"]) for rank in ranks)
        if rank_count != len(ranks):
            raise ValueError(f"SQLite import created {rank_count} ranks, expected {len(ranks)}")
        if flag_count != expected_flags:
            raise ValueError(f"SQLite import created {flag_count} flags, expected {expected_flags}")

        owner = next((rank for rank in ranks if rank["key"] == "owner"), None)
        if owner is None:
            raise ValueError("Rank ladder has no owner rank.")

        owner_flags = {
            row[0]
            for row in connection.execute(
                """
                SELECT admin_rank_flag.flag
                FROM admin_rank_flag
                JOIN admin_rank USING (admin_rank_id)
                WHERE admin_rank.name = ?
                """,
                (owner["name"],),
            )
        }
        if "HOST" not in owner_flags:
            raise ValueError("SQLite import did not grant HOST to the owner rank.")

        return {"rankCount": rank_count, "flagCount": flag_count}
    finally:
        connection.close()


def render_postgres(ranks: list[dict[str, Any]]) -> str:
    lines = [
        "-- LuaM admin rank ladder for PostgreSQL.",
        "-- Generated by Tools/generate_luam_admin_rank_sql.py. Review before applying.",
        "BEGIN;",
        "",
    ]

    for rank in ranks:
        name = sql_quote(rank["name"])
        short = sql_quote(rank["shortName"])
        lines.extend(
            [
                f"-- {rank['order']}. {rank['name']} ({rank['shortName']})",
                "DO $$",
                "BEGIN",
                f"    IF NOT EXISTS (SELECT 1 FROM admin_rank WHERE name = {name}) THEN",
                f"        INSERT INTO admin_rank (name, short_name) VALUES ({name}, {short});",
                "    END IF;",
                f"    UPDATE admin_rank SET short_name = {short} WHERE name = {name};",
                f"    DELETE FROM admin_rank_flag WHERE admin_rank_id IN (SELECT admin_rank_id FROM admin_rank WHERE name = {name});",
            ]
        )

        for flag in rank["flags"]:
            lines.append(
                "    INSERT INTO admin_rank_flag (flag, admin_rank_id) "
                f"SELECT {sql_quote(flag)}, admin_rank_id FROM admin_rank WHERE name = {name};"
            )

        lines.extend(["END $$;", ""])

    lines.append("COMMIT;")
    lines.append("")
    return "\n".join(lines)


def render_markdown(ranks: list[dict[str, Any]]) -> str:
    lines = [
        "# LuaM Admin Rank Ladder",
        "",
        "This is a local policy artifact. It does not grant anyone permissions by itself.",
        "",
        "| Order | Rank | Short | Flags | Purpose |",
        "| ---: | --- | --- | --- | --- |",
    ]

    for rank in ranks:
        flags = ", ".join(rank["flags"])
        purpose = str(rank["purpose"]).replace("|", "\\|")
        lines.append(f"| {rank['order']} | {rank['name']} | {rank['shortName']} | `{flags}` | {purpose} |")

    lines.extend(
        [
            "",
            "Operational notes:",
            "",
            "- Keep `HOST` only on `LuaM Владелец`.",
            "- Keep `PERMISSIONS` only on `LuaM Главный админ` and `LuaM Владелец`.",
            "- Prefer assigning ranks through the in-game Permissions Panel when possible.",
            "- SQL output is idempotent by rank name, but review live DB backups before applying.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    root = Path.cwd()
    input_path = root / args.input
    output_dir = root / args.output_dir

    ranks = parse_rank_yaml(input_path)
    validate_ranks(ranks)
    sqlite_check = validate_sqlite_import(ranks)

    result = {
        "ok": True,
        "checkOnly": bool(args.check_only),
        "rankCount": len(ranks),
        "sqliteCheck": sqlite_check,
        "ranks": [{"key": rank["key"], "name": rank["name"], "flags": rank["flags"]} for rank in ranks],
    }

    if args.check_only:
        if args.json:
            print(json.dumps(result, ensure_ascii=False, indent=2))
        else:
            print(f"Validated {len(ranks)} LuaM admin ranks; SQLite import created {sqlite_check['flagCount']} flags.")
        return 0

    output_dir.mkdir(parents=True, exist_ok=True)
    sqlite_path = output_dir / "luam-admin-ranks.sqlite.sql"
    postgres_path = output_dir / "luam-admin-ranks.postgres.sql"
    markdown_path = output_dir / "luam-admin-ranks.md"

    sqlite_path.write_text(render_sqlite(ranks), encoding="utf-8")
    postgres_path.write_text(render_postgres(ranks), encoding="utf-8")
    markdown_path.write_text(render_markdown(ranks), encoding="utf-8")

    result["sqlite"] = str(sqlite_path)
    result["postgres"] = str(postgres_path)
    result["markdown"] = str(markdown_path)

    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        print(f"Generated {len(ranks)} LuaM admin ranks:")
        print(f"  SQLite:   {sqlite_path}")
        print(f"  Postgres: {postgres_path}")
        print(f"  Markdown: {markdown_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
