using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NF.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class AppraisalUiFragment : BoxContainer
{
    public AppraisalUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;
    }

    public void UpdateState(List<AppraisedItem> items)
    {
        AppraisedItemContainer.RemoveAllChildren();
        EmptyLabel.Visible = items.Count == 0;
        if (EmptyLabel.Visible)
            AppraisedItemContainer.AddChild(EmptyLabel);

        // Display the newest scan first without mutating the state-owned list.
        for (var i = items.Count - 1; i >= 0; i--)
            AddAppraisedItem(items[i]);
    }

    private void AddAppraisedItem(AppraisedItem item)
    {
        var card = new PanelContainer
        {
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 5),
            StyleClasses = { "PdaListingCard" },
        };
        var row = new BoxContainer
        {
            HorizontalExpand = true,
            Orientation = LayoutOrientation.Horizontal,
            Margin = new Thickness(8, 6),
            SeparationOverride = 8,
        };

        row.AddChild(new Label
        {
            Text = item.Name,
            ToolTip = item.Name,
            HorizontalExpand = true,
            ClipText = true,
            SizeFlagsStretchRatio = 3,
        });
        row.AddChild(new Label
        {
            Text = item.AppraisedPrice,
            ToolTip = item.AppraisedPrice,
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Right,
            ClipText = true,
            SizeFlagsStretchRatio = 1,
        });

        card.AddChild(row);
        AppraisedItemContainer.AddChild(card);
    }
}
