using System.Numerics;
using Content.Client.Parallax; // Frontier: Parallax control for the background
using Content.Client.Research;
using Content.Client.UserInterface.Controls;
using Content.Shared._Goobstation.Research;
using Content.Shared.Access.Systems;
using Content.Shared.Research.Components;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Goobstation.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FancyResearchConsoleMenu : FancyWindow
{
    public Action<string>? OnTechnologyCardPressed;
    public Action? OnServerButtonPressed;

    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPrototypeManager _prototype = default!;
    [Dependency] private IPlayerManager _player = default!;

    private readonly ResearchSystem _research;
    private readonly SpriteSystem _sprite;
    private readonly AccessReaderSystem _accessReader;

    /// <summary>
    /// Console entity
    /// </summary>
    public EntityUid Entity;

    /// <summary>
    /// Currently selected tech
    /// Exists for better UI refreshing
    /// </summary>
    public ProtoId<TechnologyPrototype>? CurrentTech;

    /// <summary>
    /// All technologies and their availability
    /// </summary>
    public Dictionary<string, ResearchAvailability> List = new();

    /// <summary>
    /// Cached research points
    /// </summary>
    public int Points = 0;

    /// <summary>
    /// Is tech currently being dragged
    /// </summary>
    private bool _draggin;

    /// <summary>
    /// Global position that all tech relates to.
    /// For dragging mostly
    /// </summary>
    private Vector2 _position = DefaultPosition;

    /// <summary>
    /// Captures the initial position to use with recenter button
    /// </summary>
    private Vector2 _initialViewPosition = DefaultPosition;

    /// <summary>
    /// Tracks if first initialization has happened
    /// </summary>
    private bool _firstInitialization = true;

    /// <summary>
    /// Frontier: the distance between elements on the grid.
    /// </summary>
    private const int GridSize = 90;

    private const float MinZoom = 0.65f;
    private const float MaxZoom = 1.8f;
    private const float ZoomStep = 0.1f;

    /// <summary>
    /// Frontier: the distance between elements on the grid.
    /// </summary>
    private static readonly Vector2i DefaultPosition = Vector2i.Zero; //Frontier: 45,250 < 0,0

    private ParallaxControl _parallaxControl; // Frontier: Parallax control for the background

    private float _zoom = 1f;

    public FancyResearchConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _research = _entity.System<ResearchSystem>();
        _sprite = _entity.System<SpriteSystem>();
        _accessReader = _entity.System<AccessReaderSystem>();

        // Frontier: Initialize parallax background
        _parallaxControl = new ParallaxControl
        {
            ParallaxPrototype = "Default",
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        // Add the parallax control to the ResearchesContainer at the beginning (bottom layer)
        ResearchesContainer.AddChild(_parallaxControl);

        // Set the proper rendering order by adjusting positions in the parent's child list
        // Controls with a higher position value are drawn on top (foreground)
        // Make sure the parallax is at the bottom of the z-order (drawn first)
        _parallaxControl.SetPositionInParent(0);

        // The drag container should be in the middle
        DragContainer.SetPositionInParent(1);

        // The recenter button should be at the top of the z-order (drawn last)
        RecenterButton.SetPositionInParent(2);

        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
        DragContainer.OnKeyBindDown += OnKeybindDown;
        DragContainer.OnKeyBindUp += OnKeybindUp;
        RecenterButton.OnPressed += _ => Recenter();
        ZoomOutButton.OnPressed += _ => SetZoom(_zoom - ZoomStep);
        ZoomResetButton.OnPressed += _ => ResetZoom();
        ZoomInButton.OnPressed += _ => SetZoom(_zoom + ZoomStep);

        // Empty initialization
        UpdatePanels(List);
    }

    public void SetEntity(EntityUid entity)
        => Entity = entity;

    public void UpdatePanels(Dictionary<string, ResearchAvailability> dict)
    {
        DragContainer.RemoveAllChildren();
        List = dict;

        if (_firstInitialization && List.Count > 0)
        {
            _initialViewPosition = _position;
            _firstInitialization = false;
        }

        foreach (var tech in List)
        {
            var proto = _prototype.Index<TechnologyPrototype>(tech.Key);

            var control = new FancyResearchConsoleItem(proto, _sprite, tech.Value);
            DragContainer.AddChild(control);
            LayoutResearchCard(control, proto);
            control.SelectAction += SelectTech;

            if (tech.Key == CurrentTech)
                SelectTech(proto, tech.Value);
        }
    }

    public void UpdateInformationPanel(int points)
    {
        Points = points;

        var amountMsg = new FormattedMessage();
        amountMsg.AddMarkupOrThrow(Loc.GetString("research-console-menu-research-points-text",
            ("points", points)));
        ResearchAmountLabel.SetMessage(amountMsg);

        if (!_entity.TryGetComponent(Entity, out TechnologyDatabaseComponent? database))
            return;

        TierDisplayContainer.RemoveAllChildren();
        foreach (var disciplineId in database.SupportedDisciplines)
        {
            var discipline = _prototype.Index<TechDisciplinePrototype>(disciplineId);
            var tier = _research.GetTierCompletionPercentage(database, discipline, _prototype);

            // i'm building the small-ass control here to spare me some mild annoyance in making a new file
            var texture = new TextureRect
            {
                TextureScale = new Vector2(2, 2),
                VerticalAlignment = VAlignment.Center
            };
            var label = new RichTextLabel();
            texture.Texture = _sprite.Frame0(discipline.Icon);
            label.SetMessage(Loc.GetString("research-console-tier-percentage", ("perc", tier)));

            var control = new BoxContainer
            {
                Children =
                {
                    texture,
                    label,
                    new Control
                    {
                        MinWidth = 10
                    }
                }
            };
            TierDisplayContainer.AddChild(control);
        }
    }

    #region Drag handle
    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);

        if (!_draggin)
            return;

        _position += args.Relative;
        LayoutResearchCards();
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        if (!ResearchesContainer.GlobalRect.Contains(args.GlobalPosition))
        {
            base.MouseWheel(args);
            return;
        }

        if (args.Delta.Y == 0)
            return;

        SetZoom(_zoom + Math.Sign(args.Delta.Y) * ZoomStep);
        args.Handle();
    }

    /// <summary>
    /// Raised when LMB is pressed at <see cref="DragContainer"/>
    /// </summary>
    private void OnKeybindDown(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use)
            _draggin = true;
    }

    /// <summary>
    /// Raised when LMB is unpressed at <see cref="DragContainer"/>
    /// </summary>
    private void OnKeybindUp(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use)
            _draggin = false;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
        => _draggin ? DragMode.None : base.GetDragModeFor(relativeMousePos);
    #endregion

    /// <summary>
    /// Selects a tech prototype and opens info panel
    /// </summary>
    /// <param name="proto">Tech proto</param>
    /// <param name="availability">Tech availability</param>
    public void SelectTech(TechnologyPrototype proto, ResearchAvailability availability)
    {
        InfoContainer.RemoveAllChildren();
        if (!_player.LocalEntity.HasValue)
            return;

        CurrentTech = proto.ID;
        var control = new FancyTechnologyInfoPanel(proto, _accessReader.IsAllowed(_player.LocalEntity.Value, Entity), availability, _sprite);
        control.BuyAction += args => OnTechnologyCardPressed?.Invoke(args.ID);
        InfoContainer.AddChild(control);
    }

    /// <summary>
    /// Resets the view exactly to the initial position when the UI was first opened
    /// </summary>
    public void Recenter()
    {
        _position = _initialViewPosition;
        LayoutResearchCards();
    }

    private void ResetZoom()
    {
        _zoom = 1f;
        _position = _initialViewPosition;
        UpdateZoomLabel();
        UpdatePanels(List);
    }

    private void SetZoom(float zoom)
    {
        var newZoom = Math.Clamp(zoom, MinZoom, MaxZoom);
        if (Math.Abs(newZoom - _zoom) < 0.001f)
            return;

        var oldZoom = _zoom;
        var focus = GetZoomFocus();
        _position = focus + (_position - focus) * (newZoom / oldZoom);
        _zoom = newZoom;
        UpdateZoomLabel();
        UpdatePanels(List);
    }

    private Vector2 GetZoomFocus()
    {
        return ResearchesContainer.Size / 2f;
    }

    private void UpdateZoomLabel()
    {
        ZoomResetButton.Text = $"{Math.Round(_zoom * 100)}%";
    }

    private void LayoutResearchCards()
    {
        foreach (var child in DragContainer.Children)
        {
            if (child is not FancyResearchConsoleItem item)
                continue;

            LayoutResearchCard(item, item.Prototype);
        }
    }

    private void LayoutResearchCard(FancyResearchConsoleItem item, TechnologyPrototype proto)
    {
        item.SetZoom(_zoom);
        LayoutContainer.SetPosition(item, _position + proto.Position * GridSize * _zoom);
    }

    public override void Close()
    {
        base.Close();

        DragContainer.RemoveAllChildren();
        InfoContainer.RemoveAllChildren();
        _position = DefaultPosition;
        _initialViewPosition = DefaultPosition;
        _zoom = 1f;
        UpdateZoomLabel();
        _firstInitialization = true;
    }

    private sealed partial class DisciplineButton(TechDisciplinePrototype proto) : Button
    {
        public TechDisciplinePrototype Proto = proto;
    }
}
