using System.Linq;
using Content.Client.Administration.Managers;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Content.Shared.Administration;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Configuration;
using Robust.Shared.Console;

namespace Content.Client.Changelog
{
    [GenerateTypedNameReferences]
    public sealed partial class ChangelogWindow : FancyWindow
    {
        [Dependency] private IClientAdminManager _adminManager = default!;
        [Dependency] private ChangelogManager _changelog = default!;

        private int _populateGeneration;

        public ChangelogWindow()
        {
            RobustXamlLoader.Load(this);
            WindowTitle.AddStyleClass(StyleBase.StyleClassLabelHeading);
            Stylesheet = IoCManager.Resolve<IStylesheetManager>().SheetSpace;
        }

        protected override void Opened()
        {
            base.Opened();

            PopulateChangelog(++_populateGeneration);
        }

        protected override void EnteredTree()
        {
            base.EnteredTree();
            _adminManager.AdminStatusUpdated += OnAdminStatusUpdated;
        }

        protected override void ExitedTree()
        {
            // Invalidate an asynchronous load before this window can be reopened.
            _populateGeneration++;
            base.ExitedTree();
            _adminManager.AdminStatusUpdated -= OnAdminStatusUpdated;
        }

        private void OnAdminStatusUpdated()
        {
            TabsUpdated();
        }

        private async void PopulateChangelog(int generation)
        {
            // Changelog is not kept in memory so load it again.
            var changelogs = await _changelog.LoadChangelog();

            if (!CanApplyPopulateResult(generation, _populateGeneration, IsOpen))
                return;

            var readThroughId = changelogs
                .Where(changelog => changelog.Name == ChangelogManager.MainChangelogName)
                .SelectMany(changelog => changelog.Entries)
                .Select(entry => (int?) entry.Id)
                .Max();

            Tabs.DisposeAllChildren();

            var i = 0;
            foreach (var changelog in changelogs)
            {
                var tab = new ChangelogTab { AdminOnly = changelog.AdminOnly };
                tab.PopulateChangelog(changelog);

                Tabs.AddChild(tab);
                Tabs.SetTabTitle(i++, Loc.GetString($"changelog-tab-title-{changelog.Name}"));
            }

            VersionLabel.Text = _changelog.GetClientVersion();

            TabsUpdated();
            // Only acknowledge entries after the changelog was loaded and every visible card was built.
            if (readThroughId is { } id)
                _changelog.SaveNewReadId(id);
        }

        internal static bool CanApplyPopulateResult(int generation, int currentGeneration, bool isOpen)
        {
            return isOpen && generation == currentGeneration;
        }

        private void TabsUpdated()
        {
            var tabs = Tabs.Children.OfType<ChangelogTab>().ToArray();
            var isAdmin = _adminManager.IsAdmin(true);

            var visibleTabs = 0;
            int? firstVisible = null;
            for (var i = 0; i < tabs.Length; i++)
            {
                var tab = tabs[i];

                if (!tab.AdminOnly || isAdmin)
                {
                    Tabs.SetTabVisible(i, true);
                    visibleTabs++;
                    firstVisible ??= i;
                }
                else
                {
                    Tabs.SetTabVisible(i, false);
                }
            }

            Tabs.TabsVisible = visibleTabs > 1;

            // Current tab became invisible, select the first one that is visible
            if (!Tabs.GetTabVisible(Tabs.CurrentTab) && firstVisible != null)
            {
                Tabs.CurrentTab = firstVisible.Value;
            }

            // We are only displaying one tab, hide its header
            if (!Tabs.TabsVisible && firstVisible != null)
            {
                Tabs.SetTabVisible(firstVisible.Value, false);
            }
        }
    }

    [UsedImplicitly, AnyCommand]
    public sealed class ChangelogCommand : LocalizedCommands
    {
        [Dependency] private readonly IUserInterfaceManager _uiManager = default!;

        public override string Command => "changelog";

        public override void Execute(IConsoleShell shell, string argStr, string[] args)
        {
            _uiManager.GetUIController<ChangelogUIController>().OpenWindow();
        }
    }
}
