using System.Linq;
using System.Numerics;
using Content.Client.Resources;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.Utility;
using static Content.Client.Changelog.ChangelogManager;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client.Changelog;

[GenerateTypedNameReferences]
public sealed partial class ChangelogTab : Control
{
    [Dependency] private ChangelogManager _changelog = default!;
    [Dependency] private IResourceCache _resourceCache = default!;

    public bool AdminOnly;

    public ChangelogTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void PopulateChangelog(ChangelogManager.Changelog changelog)
    {
        ChangelogBody.RemoveAllChildren();

        var byDay = changelog.Entries
            .OrderByDescending(entry => entry.Time)
            .ThenByDescending(entry => entry.Id)
            .GroupBy(e => e.Time.ToLocalTime().Date)
            .OrderByDescending(c => c.Key);

        if (changelog.Entries.Count == 0)
        {
            ChangelogBody.AddChild(new Label
            {
                Text = Loc.GetString("changelog-empty"),
                StyleClasses = { "UiTextMuted" },
                HorizontalAlignment = HAlignment.Center,
                HorizontalExpand = true,
                Margin = new Thickness(8),
            });
            return;
        }

        foreach (var dayEntries in byDay)
        {
            var day = dayEntries.Key;

            string dayNice;
            var today = DateTime.Today;
            if (day == today)
                dayNice = Loc.GetString("changelog-today");
            else if (day == today.AddDays(-1))
                dayNice = Loc.GetString("changelog-yesterday");
            else
                dayNice = day.ToShortDateString();

            ChangelogBody.AddChild(new Label
            {
                Text = dayNice,
                StyleClasses = { StyleBase.StyleClassLabelHeading },
                Margin = new Thickness(4, 6, 0, 0)
            });

            foreach (var entry in dayEntries)
            {
                var isNew = changelog.Name == MainChangelogName && entry.Id > _changelog.LastReadId;
                var card = new PanelContainer
                {
                    HorizontalExpand = true,
                    Margin = new Thickness(4, 3, 6, 5),
                    PanelOverride = new StyleBoxFlat
                    {
                        BackgroundColor = Color.FromHex(isNew ? "#132529" : "#171D20"),
                        BorderColor = Color.FromHex(isNew ? "#4D9BA8" : "#344348"),
                        BorderThickness = new Thickness(1),
                    },
                };

                var body = new BoxContainer
                {
                    Orientation = LayoutOrientation.Vertical,
                    HorizontalExpand = true,
                    Margin = new Thickness(10, 8),
                };

                var header = new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    HorizontalExpand = true,
                };
                header.AddChild(new Label
                {
                    Text = Loc.GetString(
                        "changelog-entry-meta",
                        ("time", entry.Time.ToLocalTime().ToString("HH:mm")),
                        ("author", entry.Author)),
                    FontColorOverride = Color.FromHex("#D7E5E3"),
                    HorizontalExpand = true,
                });
                if (isNew)
                {
                    header.AddChild(new Label
                    {
                        Text = Loc.GetString("changelog-entry-new"),
                        FontColorOverride = Color.FromHex("#72C2D0"),
                        HorizontalAlignment = HAlignment.Right,
                    });
                }

                body.AddChild(header);
                body.AddChild(new PanelContainer
                {
                    StyleClasses = { StyleBase.ClassLowDivider },
                    Margin = new Thickness(0, 5, 0, 4),
                });

                foreach (var change in entry.Changes)
                {
                    var text = new RichTextLabel
                    {
                        HorizontalExpand = true,
                    };
                    text.SetMessage(FormattedMessage.FromMarkupOrThrow(change.Message));
                    body.AddChild(new BoxContainer
                    {
                        Orientation = LayoutOrientation.Horizontal,
                        HorizontalExpand = true,
                        Margin = new Thickness(2, 1, 2, 3),
                        Children =
                        {
                            GetIcon(change.Type),
                            text
                        }
                    });
                }

                card.AddChild(body);
                ChangelogBody.AddChild(card);
            }
        }
    }

    private TextureRect GetIcon(ChangelogLineType type)
    {
        var (file, color) = type switch
        {
            ChangelogLineType.Add => ("plus.svg.192dpi.png", "#6ED18D"),
            ChangelogLineType.Remove => ("minus.svg.192dpi.png", "#D16E6E"),
            ChangelogLineType.Fix => ("bug.svg.192dpi.png", "#D1BA6E"),
            ChangelogLineType.Tweak => ("wrench.svg.192dpi.png", "#6E96D1"),
            _ => throw new ArgumentOutOfRangeException(nameof(type), type, null)
        };

        return new TextureRect
        {
            Texture = _resourceCache.GetTexture(new ResPath($"/Textures/Interface/Changelog/{file}")),
            VerticalAlignment = VAlignment.Top,
            TextureScale = new Vector2(0.5f, 0.5f),
            Margin = new Thickness(2, 4, 6, 2),
            ModulateSelfOverride = Color.FromHex(color)
        };
    }
}
